-- ==========================================================
-- COMPLETE TIER-1 HARDWARE CATALOG SEED & BACKEND SYNC
-- ==========================================================

-- Enable RLS and create public read policy for products
-- SECURITY NOTE (corrected): "Public can view active products" originally
-- checked `USING (true)` with no is_active filter - draft/inactive products
-- were publicly visible. "Authenticated users can manage products" let ANY
-- logged-in user (any customer account) edit or delete the catalog, not
-- just admins. Both fixed to match what the live database actually runs.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view active products" ON public.products;
CREATE POLICY "Public can view active products"
  ON public.products FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS "Authenticated users can manage products" ON public.products;
DROP POLICY IF EXISTS "Admins full access on products fix" ON public.products;
CREATE POLICY "Admins full access on products fix"
  ON public.products FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

-- Upsert All 35+ Products into products table
INSERT INTO public.products (
  id, name, category, series, description, features, best_for, price, tier, is_active, sort_order, image_url, specifications, stock_qty, low_stock_threshold, warranty_months, tags
) VALUES
  -- 1. Inverters
  (
    'a0000000-0000-0000-0000-000000000001',
    'Deye 5kW Hybrid Inverter (SUN-5K-SG03LP1-EU)',
    'Inverters',
    'Deye SG03 Series',
    'Pure sine wave low-voltage single-phase hybrid solar inverter with dual MPPT tracker, color touch LCD screen, and generator auto-start compatibility. Zero-flicker UPS switchover.',
    ARRAY['Dual MPPT tracker (99.9% efficiency)', 'Color touch screen interface with live telemetry', 'IP65 waterproof and dustproof outdoor rated', 'Generator auto-start and peak-shaving port', 'Remote WiFi monitoring via Solarman / Deye Cloud App', '48V low voltage battery safe architecture'],
    '3-4 bedroom duplexes, executive residences, small businesses',
    '₦1,850,000',
    'premium',
    true,
    1,
    '/src/assets/bg-panel-closeup.jpg',
    '{"Rated AC Output": "5,000W Continuous / 10,000W Peak Surge", "Nominal DC Voltage": "48Vdc (40V - 60V Range)", "MPPT Trackers": "2 Trackers (125V - 425V Range)", "Max Solar PV Input": "6,500W", "Switch Time": "<4ms Seamless UPS Transfer", "Warranty": "5-Year Manufacturer Replacement Warranty", "Dimensions": "330 x 580 x 232 mm (20.5 kg)"}'::jsonb,
    18,
    3,
    60,
    ARRAY['inverter', 'hybrid', 'deye', 'solar', 'ups']
  ),
  (
    'a0000000-0000-0000-0000-000000000002',
    'Deye 8kW Hybrid Inverter (SUN-8K-SG01LP1-EU)',
    'Inverters',
    'Deye SG01 Series',
    'Heavy-duty single-phase hybrid inverter with dual MPPT inputs, supporting up to 10.4kW solar PV array and parallel multi-unit expansion for larger residences and medical facilities.',
    ARRAY['8,000W rated continuous output power', 'Dual MPPT with wide 125V-500V operating window', 'Parallel stacking up to 16 units for three-phase or single-phase', 'Smart load port for non-essential heavy appliance shedding', 'Integrated AC and DC surge protection (Type II SPD)', 'CAN / RS485 communication with all Tier-1 LiFePO4 batteries'],
    'Large duplexes, commercial labs, penthouses, heavy HVAC setups',
    '₦2,650,000',
    'premium',
    true,
    2,
    '/src/assets/feature-solar-panel.jpg',
    '{"Rated AC Output": "8,000W Continuous / 16,000W Surge (10s)", "Nominal DC Voltage": "48Vdc", "MPPT Trackers": "2 Trackers (2+2 Strings)", "Max Solar PV Input": "10,400W", "Efficiency": "97.6% Euro Efficiency", "Warranty": "5-Year Official Replacement Warranty", "Dimensions": "420 x 670 x 233 mm (32 kg)"}'::jsonb,
    12,
    2,
    60,
    ARRAY['inverter', 'hybrid', 'deye', '8kw', 'solar']
  ),
  (
    'a0000000-0000-0000-0000-000000000003',
    'Deye 12kW Three-Phase Hybrid Inverter (SUN-12K-SG04LP3-EU)',
    'Inverters',
    'Deye SG04 Series',
    'Enterprise three-phase 400V hybrid solar inverter with dual MPPT, 100% unbalanced phase output capability, and smart diesel generator auto-synchronization.',
    ARRAY['12,000W 3-Phase balanced or unbalanced AC output', 'Dual MPPT tracker supporting up to 15,600W PV array', '100% unbalanced phase output (up to 50% rated power on one phase)', 'Smart micro-grid and generator hybrid coordination', 'IP65 protection with intelligent fan thermal dissipation', 'Full cloud analytics via iOS/Android/Web portal'],
    'Commercial plazas, manufacturing facilities, hospitals, hotels',
    '₦4,150,000',
    'premium',
    true,
    3,
    '/src/assets/bg-commercial-solar.jpg',
    '{"Rated AC Output": "12,000W Three-Phase 380V/400V", "Nominal DC Voltage": "48Vdc (Low Voltage High-Safety Architecture)", "MPPT Trackers": "2 Trackers (2+1 String Inputs)", "Max Solar PV Input": "15,600W", "Parallel Capacity": "Up to 16 units stacked", "Warranty": "5-Year Enterprise Warranty", "Dimensions": "422 x 699 x 279 mm (33.6 kg)"}'::jsonb,
    8,
    2,
    60,
    ARRAY['inverter', 'three-phase', 'deye', '12kw', 'commercial']
  ),
  (
    'a0000000-0000-0000-0000-000000000004',
    'SRNE HFP4850S80-145 5kW Parallel Hybrid Inverter',
    'Inverters',
    'SRNE Top Picks',
    'Reliable, parallel-capable 5kW solar hybrid inverter with 80A MPPT charge controller, pure sine wave AC output, and dual BMS communication protocols.',
    ARRAY['5,000W continuous output / 10,000W motor surge', 'Integrated 80A MPPT solar charge controller', 'Supports parallel operation up to 6 units (30kW total)', 'Configurable AC/Solar input priority and charging current', 'Multi-stage battery charging for LiFePO4 and Tubular batteries'],
    'Residential backup, budget-conscious solar installations',
    '₦1,450,000',
    'mid',
    true,
    4,
    '/src/assets/offer-solar.jpg',
    '{"Rated AC Output": "5,000W Pure Sine Wave", "Nominal DC Voltage": "48Vdc", "Max MPPT Voltage": "145Vdc (80A)", "Parallel Capability": "Up to 6 units (Single or 3-Phase)", "Warranty": "2-Year Comprehensive Warranty"}'::jsonb,
    24,
    5,
    24,
    ARRAY['inverter', 'srne', '5kw', 'parallel', 'solar']
  ),
  (
    'a0000000-0000-0000-0000-000000000005',
    'SRNE HYP4860S100-H 6kW High-Voltage Hybrid Inverter',
    'Inverters',
    'SRNE Top Picks',
    'Next-generation high-PV-voltage hybrid inverter with 100A MPPT controller and advanced RGB status light indicator for modern energy management.',
    ARRAY['6,000W continuous AC output power', 'High PV input voltage range (120V - 500Vdc)', 'Dual AC output ports for smart sub-load management', 'Lithium battery activation via solar or utility power', 'Integrated WiFi module for mobile tracking'],
    'Medium-to-large residential setups, private clinics',
    '₦1,750,000',
    'premium',
    true,
    5,
    '/src/assets/cat-solar.jpg',
    '{"Rated AC Output": "6,000W Continuous", "Nominal DC Voltage": "48Vdc", "Max Solar PV Voltage": "500Vdc (100A MPPT)", "Max Solar PV Input": "8,000W", "Warranty": "3-Year Warranty"}'::jsonb,
    15,
    3,
    36,
    ARRAY['inverter', 'srne', '6kw', 'solar', 'hybrid']
  ),
  (
    'a0000000-0000-0000-0000-000000000006',
    'Growatt SPF 5000 ES Off-Grid Inverter',
    'Inverters',
    'Growatt SPF Series',
    'Worldwide bestseller off-grid hybrid inverter with high 450V MPPT tracker, capability to run without batteries during daytime sun, and parallel support.',
    ARRAY['5,000W pure sine wave output', 'Integrated MPPT charge controller up to 450Vdc', 'Battery-less operation during full sunlight hours', 'Parallel scalability up to 6 units (30kVA)', 'Supports CAN / RS485 communication with lithium packs'],
    'Remote homes, farmhouses, urban residences',
    '₦1,380,000',
    'mid',
    true,
    6,
    '/src/assets/bg-solar-field.jpg',
    '{"Rated AC Output": "5,000W Continuous", "Nominal Battery Voltage": "48Vdc", "Max PV Open Circuit": "450Vdc", "Warranty": "2-Year Warranty"}'::jsonb,
    20,
    4,
    24,
    ARRAY['inverter', 'growatt', '5kw', 'offgrid']
  ),
  (
    'a0000000-0000-0000-0000-000000000007',
    'Luxpower SNA5000 Wide-Voltage Hybrid Inverter',
    'Inverters',
    'Luxpower SNA Series',
    'Versatile hybrid inverter engineered specifically for areas with erratic or low grid voltage. Features dual MPPT inputs and sub-10ms UPS switchover.',
    ARRAY['5,000W continuous output / 6,000W peak PV input', 'Dual independent MPPT trackers', 'Wide grid input voltage tolerance (90V - 280V)', 'Free cloud monitoring via Luxpower App', 'Fast zero-flicker UPS changeover'],
    'Nigerian homes with unstable NEPA grid voltage',
    '₦1,420,000',
    'mid',
    true,
    7,
    '/src/assets/bg-panel-closeup.jpg',
    '{"Rated AC Output": "5,000W", "DC Battery Voltage": "48Vdc", "MPPT Trackers": "2 Trackers (100V - 480V)", "Warranty": "2-Year Warranty"}'::jsonb,
    16,
    3,
    24,
    ARRAY['inverter', 'luxpower', '5kw', 'hybrid']
  ),

  -- 2. Batteries
  (
    'a0000000-0000-0000-0000-000000000008',
    'Felicity Solar 5.12kWh 100Ah LiFePO4 Battery (FL-LPBF48100)',
    'Batteries',
    'Felicity LPBF Series',
    'Tier-1 Grade-A Lithium Iron Phosphate (LiFePO4) battery module with 6,000+ lifecycle count, built-in intelligent battery management system (BMS), and wall/rack mount design.',
    ARRAY['5,120Wh (5.12kWh) usable storage capacity', '6,000+ charge cycles at 80% Depth of Discharge (DoD)', 'Smart internal BMS with overcharge, overdischarge and thermal cutoff', 'Direct CAN / RS485 plug-and-play communication with Deye & SRNE', 'Safe non-combustible chemistry with zero maintenance required', 'Expandable in parallel up to 8 units (40.96kWh total)'],
    '3kVA - 5kVA inverter setups, overnight lighting and refrigeration',
    '₦1,450,000',
    'premium',
    true,
    8,
    '/src/assets/feature-battery.jpg',
    '{"Nominal Energy": "5.12 kWh (5,120 Wh)", "Nominal Voltage": "51.2 Vdc (16S Configuration)", "Usable Capacity": "100 Ah", "Max Charge/Discharge": "50A Recommended / 100A Max Continuous", "Cycle Life": ">6,000 Cycles @ 25°C, 80% DoD", "Communication": "CAN, RS485, RS232", "Warranty": "5-Year Official Replacement Warranty", "Dimensions": "480 x 440 x 175 mm (42 kg)"}'::jsonb,
    25,
    4,
    60,
    ARRAY['battery', 'lifepo4', 'lithium', 'felicity', '5kwh']
  ),
  (
    'a0000000-0000-0000-0000-000000000009',
    'Felicity Solar 10.24kWh 200Ah LiFePO4 Battery Wall-Mount (FL-LPBF48200)',
    'Batteries',
    'Felicity LPBF Series',
    'Sleek wall-mounted residential Powerwall battery with 10.24kWh capacity, integrated LCD status screen, high-amperage circuit breaker, and 6,000+ cycle lifespan.',
    ARRAY['10,240Wh (10.24kWh) high-density energy storage', 'Powers inverter 1.5HP AC units, freezers, and entertainment through the night', 'Built-in color LCD showing battery state of charge (SoC) and cell voltages', 'Heavy-duty DC circuit breaker for instant maintenance isolation', 'Automatic cell balancing ensuring decade-long battery longevity', 'Parallel connection support up to 6 units (61.44kWh)'],
    '5kVA - 10kVA inverters, 24/7 air conditioning and complete blackout immunity',
    '₦2,850,000',
    'premium',
    true,
    9,
    '/src/assets/bg-bundle.jpg',
    '{"Nominal Energy": "10.24 kWh", "Nominal Voltage": "51.2 Vdc", "Usable Capacity": "200 Ah", "Max Continuous Current": "150A Discharge", "Cycle Life": ">6,000 Cycles @ 80% DoD", "Display": "Integrated Multifunction LCD", "Warranty": "5-Year Official Replacement Warranty", "Dimensions": "650 x 500 x 240 mm (83 kg)"}'::jsonb,
    14,
    2,
    60,
    ARRAY['battery', 'lifepo4', 'lithium', 'felicity', '10kwh', 'powerwall']
  ),
  (
    'a0000000-0000-0000-0000-000000000010',
    'Felicity Solar 15.36kWh 300Ah Commercial Storage Battery',
    'Batteries',
    'Felicity High-Cap',
    'Commercial grade heavy-duty energy storage system with 15.36kWh capacity, dual breaker safety isolation, and high continuous discharge rating.',
    ARRAY['15,360Wh (15.36kWh) massive storage reservoir', 'Heavy-duty copper busbars for high surge motor startups', 'Dual circuit breaker and DC fuse protection', 'Grade-A automotive cells certified for 6,000+ cycles', 'Seamless communication with Deye 10kW & 12kW inverters'],
    'Commercial buildings, luxury mansions, servers and medical clinics',
    '₦4,100,000',
    'premium',
    true,
    10,
    '/src/assets/feature-battery.jpg',
    '{"Nominal Energy": "15.36 kWh", "Nominal Voltage": "51.2 Vdc", "Usable Capacity": "300 Ah", "Max Continuous Current": "200A Discharge", "Cycle Life": "6,000+ Cycles", "Warranty": "5-Year Enterprise Warranty", "Weight": "125 kg"}'::jsonb,
    6,
    2,
    60,
    ARRAY['battery', 'lifepo4', '15kwh', 'commercial', 'felicity']
  ),
  (
    'a0000000-0000-0000-0000-000000000011',
    'AlpSolarr Pulse S2 Compact Energy Storage Unit',
    'Batteries',
    'AlpSolarr Systems',
    'Compact, silent residential lithium storage unit engineered for smart homes and apartment living with smartphone telemetry.',
    ARRAY['4.8kWh usable lithium iron phosphate capacity', 'Ultra-compact footprint with silent natural convection cooling', 'App-connected Bluetooth and Wi-Fi state of charge monitoring', 'Plug and play installation with bracket kit included'],
    'Luxury apartments, smart homes, modern offices',
    '₦1,250,000',
    'mid',
    true,
    11,
    '/src/assets/bg-circuit.jpg',
    '{"Nominal Energy": "4.8 kWh", "Nominal Voltage": "48Vdc", "Cycle Life": "5,000+ Cycles", "Warranty": "3-Year Warranty"}'::jsonb,
    12,
    3,
    36,
    ARRAY['battery', 'alpsolar', 'compact', 'storage']
  ),
  (
    'a0000000-0000-0000-0000-000000000012',
    'Itel 1000W Portable Emergency Power Station',
    'Batteries',
    'Itel Power Solutions',
    'All-in-one portable power bank with pure sine wave 1000W AC outlet, fast 100W USB-C PD charging, high-lumen LED light, and solar charging input.',
    ARRAY['1,000Wh battery capacity with pure sine wave 1000W inverter', '2x AC 230V outlets, 4x USB ports, 1x 100W PD Type-C port', 'Charges from 0 to 80% in 1.5 hours via wall outlet', 'Compatible with portable solar panels for outdoor camping and field jobs', 'Digital LCD display showing exact remaining battery minutes'],
    'Remote work, field engineers, outdoor events, emergency loadshedding',
    '₦420,000',
    'entry',
    true,
    12,
    '/src/assets/bg-circuit.jpg',
    '{"Capacity": "1,000Wh (270,000mAh)", "AC Output": "1000W Pure Sine Wave (Surge 2000W)", "Solar Input": "12V-24V / 200W Max", "Weight": "9.2 kg", "Warranty": "1-Year Warranty"}'::jsonb,
    30,
    5,
    12,
    ARRAY['portable', 'powerstation', 'itel', 'emergency', 'battery']
  ),

  -- 3. Solar Panels
  (
    'a0000000-0000-0000-0000-000000000013',
    'Longi 550W Hi-MO 5 Tier-1 Mono PERC Solar Panel',
    'Solar Panels',
    'Longi Hi-MO 5',
    'Industry-benchmark Bloomberg Tier-1 monocrystalline half-cell solar module with 21.5% cell efficiency, gallium-doped wafer anti-PID technology, and 25-year power warranty.',
    ARRAY['550W peak power output under standard test conditions (STC)', '21.5% high module conversion efficiency', 'Half-cut 182mm wafer technology reduces resistive power loss', 'Superior low-light and high-temperature power yield in Nigerian weather', 'Anodized aluminum alloy frame with 5400Pa mechanical load rating', 'IP68 waterproof junction box with original MC4 connectors'],
    'Residential roofs, commercial rooftop solar arrays, solar farms',
    '₦145,000',
    'premium',
    true,
    13,
    '/src/assets/feature-solar-panel.jpg',
    '{"Peak Power (Pmax)": "550 Wp", "Open Circuit Voltage (Voc)": "49.80 V", "Short Circuit Current (Isc)": "13.98 A", "Voltage at Pmax (Vmp)": "41.95 V", "Current at Pmax (Imp)": "13.12 A", "Module Efficiency": "21.5%", "Power Warranty": "25-Year Linear Power Output Warranty", "Dimensions": "2278 x 1134 x 35 mm (27.5 kg)"}'::jsonb,
    350,
    50,
    300,
    ARRAY['solar panel', 'longi', '550w', 'mono', 'tier-1']
  ),
  (
    'a0000000-0000-0000-0000-000000000014',
    'Longi 600W Hi-MO 6 Explorer Bifacial Solar Panel',
    'Solar Panels',
    'Longi Hi-MO 6',
    'Ultra-high output bifacial HPBC cell solar panel with up to 22.8% front efficiency plus up to 25% extra energy harvest from backside reflected light.',
    ARRAY['600W nominal front power rating', 'Bifacial glass-glass structure capturing ambient reflected light', 'HPBC cell technology with zero front grid lines for maximum sunlight capture', 'Exceptional performance during hazy Hamattan and overcast rainy days', '30-Year dual-glass linear power warranty'],
    'Commercial installations, ground mounts, flat reflective rooftops',
    '₦168,000',
    'premium',
    true,
    14,
    '/src/assets/bg-commercial-solar.jpg',
    '{"Peak Power (Pmax)": "600 Wp", "Module Efficiency": "22.8%", "Bifaciality Factor": "70% ± 5%", "Warranty": "30-Year Performance Warranty", "Dimensions": "2384 x 1134 x 35 mm (32 kg)"}'::jsonb,
    180,
    30,
    360,
    ARRAY['solar panel', 'longi', '600w', 'bifacial', 'tier-1']
  ),
  (
    'a0000000-0000-0000-0000-000000000015',
    'Canadian Solar 550W HiKu6 Monocrystalline Panel',
    'Solar Panels',
    'Canadian Solar HiKu6',
    'Tier-1 high power mono module with comprehensive shading mitigation, low temperature coefficient, and certified wind load resistance.',
    ARRAY['550W high efficiency solar module', 'Low temperature coefficient (-0.34% / °C) for Nigerian tropical heat', 'Minimized micro-crack risk with multi-busbar cell design', 'High reliability with IP68 sealed bypass diodes'],
    'Residential homes, estate canopies, industrial rooftops',
    '₦148,000',
    'premium',
    true,
    15,
    '/src/assets/feature-solar-panel.jpg',
    '{"Power Rating": "550 Wp", "Efficiency": "21.3%", "Warranty": "25-Year Power Guarantee", "Dimensions": "2278 x 1134 x 35 mm (27.6 kg)"}'::jsonb,
    200,
    40,
    300,
    ARRAY['solar panel', 'canadian solar', '550w', 'tier-1']
  ),

  -- 4. Smart Locks
  (
    'a0000000-0000-0000-0000-000000000016',
    'STAMA Model K209 Elite 3D Face Recognition Smart Lock',
    'Smart Locks',
    'Elite Series',
    'Flagship luxury smart lock with 3D infrared biometric face scanning, palm-vein authentication, built-in wide-angle video intercom viewer, and military-grade encryption.',
    ARRAY['3D Structured Light Face ID unlocks in under 0.6 seconds', 'Palm-vein contactless biometric reader', 'Live 1080p video doorbell viewer with indoor color HD screen', 'Remote unlock via Tuya / SmartLife App from anywhere in the world', 'Anti-tamper alarm, fake PIN anti-peeping scramble code', 'Rechargeable 5000mAh lithium battery with 8-12 month runtime'],
    'Executive mansions, luxury penthouses, main armored security doors',
    '₦285,000',
    'premium',
    true,
    16,
    '/src/assets/bg-smartlock-elite.jpg',
    '{"Unlock Methods": "3D Face, Palm Vein, Fingerprint, Passcode, RFID Card, App, Key", "User Capacity": "100 Faces, 100 Fingerprints, 100 Passcodes, 100 Cards", "Camera": "1080p HD Wide Angle with Infrared Night Vision", "Display": "3.5-inch Color HD Indoor Screen", "Door Compatibility": "Wooden, Armored, Metal doors (40mm - 120mm thickness)", "Battery": "5000mAh Rechargeable Lithium Pack", "Warranty": "2-Year Complete Hardware Warranty"}'::jsonb,
    35,
    5,
    24,
    ARRAY['smart lock', 'face id', 'stama', 'k209', 'biometric', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000017',
    'STAMA Model S7 Premier-Lux Custom Israeli Edition',
    'Smart Locks',
    'Elite Series',
    'Custom Israeli engineering edition designed for executive apartments and premium shortlets needing ultra-fast access and IP66 weatherproofing.',
    ARRAY['High-precision 3D facial recognition', 'Semiconductor live fingerprint sensor with 360° recognition', 'IP66 waterproof performance suited for exposed exterior doors', 'Encrypted RFID access cards and mechanical override key', 'Entry record and real-time smartphone notification logs'],
    'Executive apartments, premium shortlets, outdoor security doors',
    '₦300,000',
    'premium',
    true,
    17,
    '/src/assets/bg-smartlock-elite.jpg',
    '{"Unlock Modes": "Face ID, Fingerprint, RFID Card, Passcode, App, Mechanical Key", "Waterproof Rating": "IP66 Weather-Resistant", "Mortise": "Stainless Steel 6068 Anti-Drill Mortise", "Warranty": "2-Year Warranty"}'::jsonb,
    20,
    3,
    24,
    ARRAY['smart lock', 'stama', 's7', 'waterproof', 'face id']
  ),
  (
    'a0000000-0000-0000-0000-000000000018',
    'STAMA Model D20 Apex-Lux Biometric Smart Lock',
    'Smart Locks',
    'Apex Series',
    'Popular smart security lock for homes and apartments seeking advanced biometric access, mobile app control, and keyless convenience.',
    ARRAY['Rapid fingerprint recognition under 0.4 seconds', 'Passcode entry with temporary visitor PIN generation', 'Wi-Fi app control with remote unlock authorization', 'Built-in electronic doorbell chime', 'Sturdy zinc alloy body with scratch-resistant tempered glass keypad'],
    'Family homes, apartments, executive offices',
    '₦280,000',
    'mid',
    true,
    18,
    '/src/assets/bg-smartlock-apex.jpg',
    '{"Unlock Modes": "Fingerprint, Passcode, Card, Tuya App, Physical Key", "Capacity": "100 Fingerprints, 50 RFID Cards", "Material": "High-Density Zinc Alloy", "Warranty": "2-Year Warranty"}'::jsonb,
    40,
    6,
    24,
    ARRAY['smart lock', 'stama', 'd20', 'fingerprint', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000019',
    'STAMA Model H11 Apex Video Intercom Smart Lock',
    'Smart Locks',
    'Apex Series',
    'Integrated smart lock featuring an internal video screen, automatic snapshot of visitors on doorbell press, and two-way remote smartphone intercom.',
    ARRAY['Integrated HD camera and indoor color screen', 'Pushes photo snapshot to your smartphone whenever doorbell is rung', 'Fingerprint, RFID card, and temporary access codes', 'Automatic locking mechanism when door closes'],
    'Modern residences, private lounges, serviced apartments',
    '₦280,000',
    'mid',
    true,
    19,
    '/src/assets/bg-smartlock-apex.jpg',
    '{"Camera": "HD Night-Vision Camera with Two-Way Audio", "Screen": "Indoor Color Display", "Unlock": "Face, Fingerprint, Passcode, App, Card, Key", "Warranty": "2-Year Warranty"}'::jsonb,
    25,
    4,
    24,
    ARRAY['smart lock', 'stama', 'h11', 'video doorbell', 'camera']
  ),
  (
    'a0000000-0000-0000-0000-000000000020',
    'STAMA SL02 Slim-Profile Smart Lock for Glass & Aluminum Doors',
    'Smart Locks',
    'Pro Series',
    'Slim 38mm profile smart lock designed specifically for modern narrow-frame aluminum doors, sliding patio doors, and wooden entryways.',
    ARRAY['Narrow European mortise fits aluminum and sliding doors', 'Fingerprint scanner integrated directly onto handle grip', 'TTL / Tuya mobile app control with access timestamp logs', 'Staff attendance tracking mode for office environments'],
    'Narrow aluminum frame doors, sliding patio doors, modern offices',
    '₦220,000',
    'affordable',
    true,
    20,
    '/src/assets/bg-smartlock-pro.jpg',
    '{"Lock Width": "38 mm Narrow Profile", "Door Types": "Aluminum Profile, Sliding Doors, Wooden Doors", "App Control": "TTlock / Tuya App with Bluetooth & Gateway", "Warranty": "18-Month Warranty"}'::jsonb,
    30,
    5,
    18,
    ARRAY['smart lock', 'stama', 'sl02', 'aluminum door', 'sliding door']
  ),
  (
    'a0000000-0000-0000-0000-000000000021',
    'STAMA TF5 Connected Shortlet Access Smart Lock',
    'Smart Locks',
    'Pro Series',
    'The ideal smart lock for Airbnb hosts, shortlets, and hotel operators. Generate time-limited PIN codes remotely without needing active internet at the lock.',
    ARRAY['Offline time-bound OTP passcode generation (starts & expires on check-in/out)', 'BLE Bluetooth app control plus optional Wi-Fi bridge', 'RFID keycards for staff and guests', 'Audit trail logs showing exact unlock timestamp and user name'],
    'Airbnb shortlets, rental apartments, boutique hotels, office rooms',
    '₦220,000',
    'affordable',
    true,
    21,
    '/src/assets/bg-smartlock-pro.jpg',
    '{"Passcode Types": "Timed, Permanent, One-time, Cyclic, Custom", "Communication": "Bluetooth 5.0 BLE (Gateway compatible)", "Battery": "4x AA Alkaline (12-Month Battery Life)", "Warranty": "18-Month Warranty"}'::jsonb,
    45,
    8,
    18,
    ARRAY['smart lock', 'stama', 'tf5', 'airbnb', 'shortlet', 'hotel']
  ),
  (
    'a0000000-0000-0000-0000-000000000022',
    'STAMA N22 Accessible Biometric Security Lock',
    'Smart Locks',
    'Pro Series',
    'Clean, reliable smart lock with fast biometric fingerprint scanner, backlit passcode keypad, and long-lasting battery performance.',
    ARRAY['Semiconductor fingerprint sensor with 0.3s response', 'Backlit capacitive keypad with anti-peep decoy PINs', 'Emergency Type-C jumpstart port if batteries run flat', 'Mechanical key backup included'],
    'Bedrooms, internal master suites, private offices',
    '₦180,000',
    'affordable',
    true,
    22,
    '/src/assets/bg-smartlock-pro.jpg',
    '{"Fingerprint Capacity": "100 Users", "Card Capacity": "50 Cards", "Warranty": "1-Year Warranty"}'::jsonb,
    32,
    5,
    12,
    ARRAY['smart lock', 'stama', 'n22', 'fingerprint']
  ),
  (
    'a0000000-0000-0000-0000-000000000023',
    'STAMA V80 Heavy-Duty Smart Gate & Security Lock',
    'Smart Locks',
    'Base Series',
    'Rugged double-sided biometric lock for exterior iron gates, perimeter fences, and compound entry points with waterproof sealing.',
    ARRAY['Dual-sided fingerprint recognition (protects both entry & exit sides)', 'Weather-sealed IP65 waterproof zinc casing', 'Wireless remote control fob included for unlocking from car or porch', 'Works on conventional iron gates, wooden fence doors, and security grilles'],
    'Compound pedestrian gates, external metal security doors',
    '₦216,000',
    'mid',
    true,
    23,
    '/src/assets/bg-smartlock-base.jpg',
    '{"Access Sides": "Dual Biometric (Front & Back)", "Waterproofing": "IP65 Outdoor Gate Ready", "Remote": "433MHz RF Remote Included", "Warranty": "18-Month Warranty"}'::jsonb,
    18,
    3,
    18,
    ARRAY['smart lock', 'gate lock', 'stama', 'v80', 'waterproof', 'iron gate']
  ),
  (
    'a0000000-0000-0000-0000-000000000024',
    'STAMA G290 Frameless Glass Door Smart Lock',
    'Smart Locks',
    'Base Series',
    'Clamp-on biometric lock for frameless glass office doors. Requires zero drilling or cutting into the glass panel.',
    ARRAY['Clamp-on installation with zero glass drilling required', 'Fingerprint, passcode, and RFID card authentication', 'Built-in doorbell and attendance logging', 'Suitable for double or single swing glass doors'],
    'Corporate offices, boardroom doors, commercial shopping plazas',
    '₦198,000',
    'entry',
    true,
    24,
    '/src/assets/bg-smartlock-base.jpg',
    '{"Glass Thickness": "10mm - 12mm Frameless Glass", "Installation": "No Hole Drilling Clamp System", "Warranty": "1-Year Warranty"}'::jsonb,
    22,
    4,
    12,
    ARRAY['smart lock', 'glass door', 'stama', 'g290', 'office']
  ),
  (
    'a0000000-0000-0000-0000-000000000025',
    'STAMA KT14 Rugged Biometric Smart Padlock',
    'Smart Locks',
    'Smart Padlocks',
    'Portable, heavy-duty smart padlock with IP67 submersible waterproof rating, 0.5s fingerprint sensor, and stainless steel shackle.',
    ARRAY['Instant 0.5s fingerprint recognition (up to 50 fingers)', 'IP67 submersible waterproof rating for all weather use', 'Rechargeable battery lasts up to 6 months per single charge', 'Hardened steel shackle resists bolt cutters and sawing'],
    'Solar battery cages, warehouse gates, shipping containers, tool sheds',
    '₦80,000',
    'entry',
    true,
    25,
    '/src/assets/bg-smartlock-accessory.jpg',
    '{"Protection": "IP67 Submersible Waterproof", "Material": "Zinc Alloy Body + Stainless Steel Shackle", "Battery": "USB Rechargeable Lithium", "Warranty": "1-Year Warranty"}'::jsonb,
    50,
    10,
    12,
    ARRAY['padlock', 'biometric', 'stama', 'kt14', 'waterproof', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000026',
    'STAMA Smart Hotel Access & Management Ecosystem',
    'Smart Locks',
    'Hotel Management Suite',
    'Full turnkey hotel digital access system including smart RFID/BLE locks, USB card encoder, central web management portal, and energy-saving switches.',
    ARRAY['Centralized front-desk guest check-in and card encoding', 'Generate digital mobile keys for guest smartphone check-in', 'Real-time guest access logging and room occupancy status', 'Energy-saving room power switches activate only on valid room card'],
    'Hotels, guest houses, serviced apartments, resort suites',
    '₦1,450,000',
    'premium',
    true,
    26,
    '/src/assets/bg-smartlock-hotel.jpg',
    '{"System Includes": "10x Hotel Smart Locks, 1x Card Encoder, 100x RFID Cards, Management Software", "Software": "Windows PC Software & Cloud Web Portal", "Warranty": "2-Year Enterprise Warranty"}'::jsonb,
    10,
    2,
    24,
    ARRAY['hotel', 'smart lock', 'stama', 'hospitality', 'access control']
  ),

  -- 5. Smart Home Automation & IoT
  (
    'a0000000-0000-0000-0000-000000000027',
    'Tioga 8-Gang WiFi & Zigbee Smart Glass Touch Wall Switch',
    'Home Automation',
    'Smart Touch Series',
    'Luxury tempered glass touch switch with 8 independent circuits, smartphone app remote control, timer automation, and Google Home/Alexa voice sync.',
    ARRAY['8 gang independent touch channels on a standard double-gang plate', 'Scratch-resistant tempered crystal glass with subtle LED backlighting', 'Remote control, grouping and scheduling from Tuya / SmartLife App', 'Voice control with Amazon Alexa and Google Assistant', 'Power status memory remembers state after power restoration'],
    'Living rooms, master bedrooms, executive reception areas',
    '₦68,000',
    'mid',
    true,
    27,
    '/src/assets/feature-smart-automation-device.jpg',
    '{"Gang Channels": "8 Channels (Up to 500W per gang)", "Wireless Protocol": "WiFi 2.4GHz + Zigbee 3.0", "Material": "Flame-Retardant PC + Tempered Glass", "Voltage": "100V - 250V AC 50/60Hz", "Warranty": "2-Year Warranty"}'::jsonb,
    45,
    8,
    24,
    ARRAY['smart switch', 'automation', 'wifi', 'zigbee', 'tioga iot']
  ),
  (
    'a0000000-0000-0000-0000-000000000028',
    'Tioga 4-Gang Zigbee Smart Wall Touch Switch',
    'Home Automation',
    'Smart Touch Series',
    'Modern 4-gang smart wall switch with capacitive touch sensors, customizable scene triggers, and energy consumption telemetry.',
    ARRAY['4 touch channels with smooth haptic feedback', 'Ultra-low latency mesh networking via Zigbee hub', 'Automation scenes (e.g., All Lights Off on leaving home)', 'Works with or without neutral wire options'],
    'Bedrooms, corridors, dining rooms',
    '₦48,000',
    'mid',
    true,
    28,
    '/src/assets/feature-control-panel.jpg',
    '{"Channels": "4 Gangs", "Wireless": "Zigbee 3.0", "Warranty": "2-Year Warranty"}'::jsonb,
    60,
    10,
    24,
    ARRAY['smart switch', 'zigbee', '4 gang', 'automation']
  ),
  (
    'a0000000-0000-0000-0000-000000000029',
    'Tioga 1-Gang WiFi Smart Relay Switch (In-Wall)',
    'Home Automation',
    'Smart Switch Base',
    'Compact in-wall micro smart relay that converts any existing conventional light switch or socket into a smartphone-controlled smart device.',
    ARRAY['Hides neatly inside standard junction box behind your existing wall switch', 'Preserves original physical switch functionality while adding phone control', '16A maximum load capacity suitable for lighting or appliances', 'Timer and countdown automation'],
    'Retrofitting existing home switches without replacing wall plates',
    '₦18,000',
    'entry',
    true,
    29,
    '/src/assets/feature-smart-app.jpg',
    '{"Max Current": "16A (3,500W Max)", "Protocol": "WiFi 2.4GHz", "Dimensions": "41 x 41 x 20 mm", "Warranty": "1-Year Warranty"}'::jsonb,
    120,
    20,
    12,
    ARRAY['relay', 'smart switch', 'wifi', 'retrofit', 'automation']
  ),
  (
    'a0000000-0000-0000-0000-000000000030',
    'Tioga Granite Smart Control Panel Display with Voice',
    'Home Automation',
    'Smart Control Hubs',
    'Wall-mounted 4-inch smart touch panel with built-in Zigbee hub, ambient lighting control, HVAC thermostat integration, and voice assistant.',
    ARRAY['4-inch multi-touch IPS color touchscreen display', 'Integrated Zigbee 3.0 mesh gateway connects up to 100 devices', 'Control lights, curtains, music, locks, and solar inverter status from one panel', 'Two-way intercom function between rooms'],
    'Master bedrooms, living room foyers, executive offices',
    '₦215,000',
    'premium',
    true,
    30,
    '/src/assets/feature-tablet-monitor.jpg',
    '{"Display": "4-inch IPS HD Touchscreen (480 x 480)", "Wireless": "WiFi + Zigbee 3.0 + Bluetooth", "Built-in Gateway": "Yes (Up to 100 sub-devices)", "Warranty": "2-Year Warranty"}'::jsonb,
    15,
    3,
    24,
    ARRAY['smart panel', 'display', 'hub', 'zigbee', 'automation', 'tioga iot']
  ),
  (
    'a0000000-0000-0000-0000-000000000031',
    'Tioga Smart WiFi Water Heater 40A Heavy-Duty Switch',
    'Home Automation',
    'Home Automation',
    'Heavy-duty 40A smart switch built specifically for high-wattage water heaters (boilers), air conditioners, and pumping machines.',
    ARRAY['40A / 8,000W heavy-duty load capacity', 'Automate water heater to turn on 30 minutes before wake-up and auto-off', 'Tempered glass touch front plate with flame retardant housing', 'Eliminates wasted electricity from forgotten water heaters'],
    'Water heaters (boilers), water pumping machines, 2HP+ AC units',
    '₦38,000',
    'entry',
    true,
    31,
    '/src/assets/feature-smart-automation-device.jpg',
    '{"Max Current": "40A Resistive Load (8,000W Max)", "Protocol": "WiFi 2.4GHz", "Warranty": "18-Month Warranty"}'::jsonb,
    40,
    6,
    18,
    ARRAY['boiler switch', 'water heater', '40a', 'heavy duty', 'automation']
  ),

  -- 6. CCTV & Surveillance
  (
    'a0000000-0000-0000-0000-000000000032',
    'Tioga 1080p Smart WiFi Indoor Pan/Tilt Security Camera',
    'CCTV',
    'Smart Vision',
    'Compact 360° pan-tilt indoor smart security camera with AI human motion tracking, infrared night vision, and two-way audio talk.',
    ARRAY['Full 1080p HD video with 355° horizontal and 90° vertical rotation', 'AI human detection auto-tracks movement across the room', 'Two-way audio allows talking with family or pets through smartphone', 'Clear infrared night vision up to 10 meters in pitch darkness', 'MicroSD card (up to 128GB) and secure encrypted cloud recording'],
    'Nurseries, living rooms, shops, reception desks, pet monitoring',
    '₦35,000',
    'entry',
    true,
    32,
    '/src/assets/feature-cctv.jpg',
    '{"Resolution": "1080p Full HD (1920 x 1080)", "FOV": "360° Panoramic View (Pan/Tilt)", "Night Vision": "IR LEDs up to 10m", "Audio": "Built-in Mic and Speaker", "Storage": "MicroSD slot up to 128GB + Cloud", "Warranty": "1-Year Warranty"}'::jsonb,
    55,
    10,
    12,
    ARRAY['cctv', 'camera', 'indoor', 'wifi', 'ptz', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000033',
    'Tioga 2K HD Outdoor Weatherproof IP66 Security Bullet Camera',
    'CCTV',
    'Pro Surveillance',
    'Heavy-duty outdoor security camera with 2K crystal resolution, full-color spotlight night vision, deterrence siren, and IP66 weatherproof metal housing.',
    ARRAY['2K QHD (2560 x 1440) ultra-crisp resolution', 'Full-color night vision with dual motion-activated spotlights', 'Active deterrence with customizable strobe light and loud siren alarm', 'IP66 aluminum weatherproof casing withstands heavy tropical downpours', 'Dual external WiFi antennas for long-distance perimeter signal strength'],
    'Compound perimeters, driveway gates, parking lots, warehouses',
    '₦58,000',
    'mid',
    true,
    33,
    '/src/assets/feature-security.jpg',
    '{"Resolution": "2K QHD (4 Megapixels)", "Weatherproofing": "IP66 Heavy Rain & Dust Proof", "Night Vision": "30m Full Color Spotlight + IR", "Alarm": "Motion Siren & Flashing Strobe", "Warranty": "2-Year Warranty"}'::jsonb,
    38,
    6,
    24,
    ARRAY['cctv', 'camera', 'outdoor', 'ip66', '2k', 'bullet', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000034',
    'Tioga 4MP Vandal-Proof Commercial Dome Camera',
    'CCTV',
    'Pro Surveillance',
    'IK10 vandal-proof discreet dome camera with wide-angle lens, Power over Ethernet (PoE), and high-resolution face capture.',
    ARRAY['IK10 vandal-resistant impact rated glass dome', '110° wide-angle lens for full room coverage with zero blind spots', 'PoE (Power over Ethernet) support for single-cable clean installation', 'Smart face and vehicle classification AI'],
    'Retail supermarkets, office corridors, bank branches, schools',
    '₦64,000',
    'mid',
    true,
    34,
    '/src/assets/offer-security.jpg',
    '{"Resolution": "4MP (2560 x 1440)", "Vandal Rating": "IK10 Impact Proof", "Power": "12Vdc / PoE (802.3af)", "Warranty": "2-Year Warranty"}'::jsonb,
    28,
    4,
    24,
    ARRAY['cctv', 'dome camera', 'vandal proof', 'commercial', 'security']
  ),
  (
    'a0000000-0000-0000-0000-000000000035',
    'Tioga Smart Universal WiFi IR/RF Remote Controller Hub',
    'Home Automation',
    'Smart Accessories',
    'Replaces all your physical TV, Air Conditioner, and decoder remotes with your smartphone and voice control.',
    ARRAY['360° omnidirectional infrared coverage controls ACs, TVs, soundbars', '433MHz RF transmitter controls motorized curtains and gate remotes', 'Set temperature schedules so AC turns on before you arrive home', 'Pre-loaded with 50,000+ appliance brands'],
    'Automating split AC units, home entertainment systems',
    '₦24,000',
    'entry',
    true,
    35,
    '/src/assets/hero-smart-home.jpg',
    '{"Coverage": "8m 360° IR Radius + 433MHz RF", "Compatibility": "Universal (LG, Samsung, Panasonic, Gree, Sony, etc.)", "Warranty": "1-Year Warranty"}'::jsonb,
    60,
    10,
    12,
    ARRAY['remote hub', 'ir remote', 'automation', 'ac control', 'tioga iot']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  series = EXCLUDED.series,
  description = EXCLUDED.description,
  features = EXCLUDED.features,
  best_for = EXCLUDED.best_for,
  price = EXCLUDED.price,
  tier = EXCLUDED.tier,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  image_url = EXCLUDED.image_url,
  specifications = EXCLUDED.specifications,
  stock_qty = EXCLUDED.stock_qty,
  low_stock_threshold = EXCLUDED.low_stock_threshold,
  warranty_months = EXCLUDED.warranty_months,
  tags = EXCLUDED.tags,
  updated_at = NOW();
