-- ==============================================================================
-- 002_seed_srne_catalog.sql
-- Complete catalog of all 48 authentic SRNE products with exact pricelist prices,
-- manufacturer images, and full technical specifications.
-- ==============================================================================

INSERT INTO public.products (
    id,
    name,
    category,
    series,
    description,
    features,
    best_for,
    price,
    tier,
    is_active,
    image_url,
    tags,
    specifications,
    stock_qty,
    warranty_months
) VALUES
(
    'a0000000-0000-0000-0000-000000000101',
    'SRNE 60kW Three-Phase C&I Hybrid Solar Storage Inverter (IESP600SH3)',
    'Inverters',
    'SRNE C&I Storage Series',
    'High-capacity 60kW three-phase commercial and industrial (C&I) hybrid storage inverter with 150-820Vdc high-voltage battery range, 4 MPPT inputs (600Vdc rated), 6ms ultra-fast switch time, and 98.1% maximum efficiency.',
    ARRAY['60kW continuous 3-phase commercial rated output power', 'Wide high-voltage battery operating range: 150Vdc - 820Vdc', '4 independent MPPT trackers with 600Vdc rated PV input voltage', '6ms seamless UPS switch time for critical commercial loads', 'Max charge / discharge current: 75A + 75A; Max PV input current: 40A * 4', 'Integrated diesel generator control, peak-shaving, and grid export limiting', '5-Year manufacturer replacement warranty'],
    'Factories, commercial plazas, hotels, schools, hospitals, and large corporate facilities',
    '₦6,988,000',
    'premium',
    true,
    '/products/srne/srne-inv-iesp-60kw.webp',
    ARRAY['inverter', 'srne', '60kw', 'three-phase', 'c&i', 'commercial', 'high-voltage', 'hybrid'],
    '{"Rated Output Power":"60,000W (60kW) 3-Phase","Battery Voltage Range":"150 - 820Vdc","Rated PV Input Voltage":"600Vdc * 4 Trackers","Switch Time":"6ms Seamless UPS","Max Charge / Discharge":"75A + 75A","Max PV Input Current":"40A * 4","Protection":"IP65 Outdoor Rated","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000102',
    'SRNE Ket 61.4kWh 614.4V High-Voltage Commercial LiFePO4 Battery System (Ket60A)',
    'Batteries',
    'SRNE C&I Storage Series',
    'Industrial-grade high-voltage LiFePO4 energy storage system comprising 12 series battery modules with 61.4kWh total capacity, 614.4V nominal voltage, and multi-layer BMS protection.',
    ARRAY['61.4kWh gross storage capacity (12 modules in series)', '614.4V high-voltage nominal system bus', '100A maximum discharge current / 70A maximum charge current', 'Standard IP20 industrial indoor cabinet enclosure', 'Multi-level safety architecture with dual contactors & DC circuit breaker', '10-Year manufacturer performance warranty'],
    'Commercial energy storage, factory backup, and peak-shaving systems',
    '₦16,140,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket60a.webp',
    ARRAY['battery', 'srne', '61kwh', 'high-voltage', 'commercial', 'ket', 'lifepo4'],
    '{"System Energy":"61.4kWh","Module Qty in Series":"12 PCS","Nominal Voltage":"614.4V","Max Discharge Current":"100A","Max Charge Current":"70A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000103',
    'SRNE Ket 63kWh 307.2V High-Voltage LiFePO4 Energy Storage System (Ket60B)',
    'Batteries',
    'SRNE C&I Storage Series',
    'High-power 63kWh commercial LiFePO4 battery system with 307.2V nominal voltage, 6 series battery modules, and heavy-duty 200A charging / 150A discharging capability.',
    ARRAY['63kWh total usable energy storage capacity', '6 modules in series (307.2V system nominal voltage)', 'High continuous current: 150A discharging / 200A fast charging', 'Heavy-duty DC busbar interconnects with Tuya Cloud remote monitoring', '10-Year manufacturer performance warranty'],
    'Commercial complexes, private mini-grids, and high-demand energy storage',
    '₦15,424,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket60b.webp',
    ARRAY['battery', 'srne', '63kwh', 'high-voltage', 'commercial', 'ket', 'lifepo4'],
    '{"System Energy":"63kWh","Module Qty in Series":"6 PCS","Nominal Voltage":"307.2V","Max Discharge Current":"150A","Max Charge Current":"200A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000104',
    'SRNE Ket 96.5kWh 307.2V Commercial LiFePO4 Battery System (Ket96C)',
    'Batteries',
    'SRNE C&I Storage Series',
    'Large-capacity 96.5kWh commercial LiFePO4 storage system with 307.2V nominal voltage, 6 series modules, and dual 200A charge and discharge current capability.',
    ARRAY['96.5kWh industrial-tier energy capacity', '6 modules in series configuration at 307.2V nominal', '200A maximum discharge / 200A maximum charge continuous current', 'Advanced thermal management and cloud-connected telemetry', '10-Year manufacturer performance warranty'],
    'Factories, estates, agribusiness, and medium-scale industrial plants',
    '₦19,233,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket96c.webp',
    ARRAY['battery', 'srne', '96kwh', 'high-voltage', 'industrial', 'ket', 'lifepo4'],
    '{"System Energy":"96.5kWh","Module Qty in Series":"6 PCS","Nominal Voltage":"307.2V","Max Discharge Current":"200A","Max Charge Current":"200A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000105',
    'SRNE Ket 126kWh 614.4V High-Voltage LiFePO4 Energy Storage System (Ket120B)',
    'Batteries',
    'SRNE C&I Storage Series',
    'Brand new high-voltage 126kWh commercial energy storage system with 12 modules in series at 614.4V nominal voltage, 150A discharging, and 200A fast charging.',
    ARRAY['126kWh high-density energy storage system', '12 modules in series yielding 614.4V nominal bus', '150A maximum discharge / 200A maximum charge current', 'Precision cell balancing, temperature sensor network, and Tuya Cloud monitoring', '10-Year manufacturer performance warranty'],
    'Manufacturing plants, shopping centers, cold-storage facilities, and micro-grids',
    '₦28,910,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket120b.webp',
    ARRAY['battery', 'srne', '126kwh', 'high-voltage', 'industrial', 'ket', 'lifepo4'],
    '{"System Energy":"126kWh","Module Qty in Series":"12 PCS","Nominal Voltage":"614.4V","Max Discharge Current":"150A","Max Charge Current":"200A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000106',
    'SRNE Ket 192.9kWh 614.4V Industrial High-Voltage Battery Storage (Ket192C)',
    'Batteries',
    'SRNE C&I Storage Series',
    'Heavy-duty 192.9kWh C&I energy storage cabinet system featuring 12 series modules at 614.4V nominal voltage, 200A continuous discharge, and 200A charge rate.',
    ARRAY['192.9kWh massive commercial capacity in engineered rack cabinet', '614.4V system nominal voltage with 12 modules in series', 'Full 200A charge and 200A discharge continuous rate', 'Integrated emergency trip, smoke detection, and remote telemetry', '10-Year manufacturer performance warranty'],
    'Heavy industrial power backup, grid-interactive peak shaving, and high-load facilities',
    '₦36,482,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket192c.webp',
    ARRAY['battery', 'srne', '192kwh', 'industrial', 'high-voltage', 'c&i', 'lifepo4'],
    '{"System Energy":"192.9kWh","Module Qty in Series":"12 PCS","Nominal Voltage":"614.4V","Max Discharge Current":"200A","Max Charge Current":"200A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000107',
    'SRNE Ket 209kWh 665.6V Flagship Industrial Battery Energy Storage System (Ket209C)',
    'Batteries',
    'SRNE C&I Storage Series',
    'SRNE flagship 209kWh high-voltage energy storage system with 13 series battery modules at 665.6V nominal voltage, 200A charge/discharge current, and utility-grade BMS protection.',
    ARRAY['209kWh utility-class energy capacity for enterprise facilities', '13 series modules delivering 665.6V nominal bus voltage', 'Full 200A continuous charge and discharge capability', 'Integrated multi-zone BMS with automated isolation and fire-safe enclosure', '10-Year manufacturer performance warranty'],
    'Utility scale solar installations, large industrial factories, and estate mini-grids',
    '₦39,187,000',
    'premium',
    true,
    '/products/srne/srne-bat-ket209c.webp',
    ARRAY['battery', 'srne', '209kwh', 'flagship', 'high-voltage', 'industrial', 'lifepo4'],
    '{"System Energy":"209kWh","Module Qty in Series":"13 PCS","Nominal Voltage":"665.6V","Max Discharge Current":"200A","Max Charge Current":"200A","Protection Degree":"IP20","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000080',
    'SRNE 5kW 48V Pure Sine Wave Solar Inverter (AFP4850S100-H)',
    'Inverters',
    'SRNE AFP Series',
    'High-frequency pure sine wave 5kW 48V solar inverter charger featuring 80A MPPT solar charging, 500Vdc maximum PV open circuit voltage, and parallel support up to 6 units.',
    ARRAY['5,000W continuous pure sine wave AC output', '80A MPPT charge controller with 500Vdc max PV open circuit rating', 'Parallels up to 6 units (up to 30kW single or three-phase)', 'Dual activation mechanism for LiFePO4 battery packs via solar or mains', '2-Year manufacturer replacement warranty'],
    'Homes, duplexes, retail stores, and standard 48V solar installations',
    '₦458,000',
    'mid',
    true,
    '/products/srne/srne-inv-afp-5kw.webp',
    ARRAY['inverter', 'srne', '5kw', 'mppt', 'hybrid', 'solar', 'parallel'],
    '{"Rated AC Output":"5,000W Pure Sine Wave","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"80A","Max PV Open Circuit Voltage":"500Vdc","Parallel Capability":"Up to 6 units","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000081',
    'SRNE 6kW 48V IP65 Waterproof Hybrid Inverter (AEP4860S135-H)',
    'Inverters',
    'SRNE AEP Series',
    'Outdoor-ready IP65 waterproof 6kW 48V solar hybrid inverter with large 135A MPPT charge controller, 500Vdc PV input, and parallel scaling up to 6 units.',
    ARRAY['6,000W continuous output with IP65 all-weather protection', '135A high-current MPPT solar charger for rapid battery recharge', '500Vdc high-voltage PV open circuit design', 'Parallels up to 6 units (up to 36kW total)', '5-Year manufacturer replacement warranty'],
    'Outdoor installations, humid or coastal environments, and premium residences',
    '₦657,000',
    'premium',
    true,
    '/products/srne/srne-inv-aep-6kw.webp',
    ARRAY['inverter', 'srne', '6kw', 'ip65', 'waterproof', 'hybrid', 'parallel'],
    '{"Rated AC Output":"6,000W","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"135A","Max PV Open Circuit Voltage":"500Vdc","Protection":"IP65 Waterproof / Dustproof","Parallel Capability":"Up to 6 units","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000110',
    'SRNE 20kW 48V Three-Phase MPPT Inverter Charger (ASP48200SH3)',
    'Inverters',
    'SRNE ASP Series',
    'High-output 20kW 48V three-phase solar inverter charger with massive 360A MPPT charging, dual MPPT trackers with 160-800V operating range, and industrial-grade power electronics.',
    ARRAY['20,000W continuous 3-phase pure sine wave output', '360A high-capacity MPPT solar charger', 'Dual MPPT trackers with 160~800V / 160~800V wide operating voltage', 'Safe low-voltage 48V battery architecture with rapid DC transfer', '2-Year official manufacturer replacement warranty'],
    'Commercial complexes, large luxury homes, supermarkets, and workshops',
    '₦2,706,000',
    'premium',
    true,
    '/products/srne/srne-inv-asp-20kw.webp',
    ARRAY['inverter', 'srne', '20kw', 'three-phase', 'asp', 'commercial', 'mppt'],
    '{"Rated AC Output":"20,000W (20kW) 3-Phase","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"360A","MPPT Voltage Range":"160 ~ 800V / 160 ~ 800V","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000086',
    'SRNE 20kW 48V IP65 Commercial Hybrid Inverter (HESP48200SH3)',
    'Inverters',
    'SRNE HESP Series',
    'Flagship 20kW 48V three-phase commercial hybrid inverter with IP65 waterproof housing, 350A MPPT charger, dual 160-800V MPPT trackers, and 5-year official warranty.',
    ARRAY['20,000W continuous 3-phase hybrid grid-tied and off-grid bidirectional operation', '350A high-efficiency MPPT solar charging capacity', 'Dual high-voltage MPPT trackers: 160~800V / 160~800V', 'IP65 waterproof outdoor enclosure with intelligent thermal management', '5-Year official manufacturer warranty'],
    'Large corporate estates, commercial buildings, schools, and filling stations',
    '₦4,007,000',
    'premium',
    true,
    '/products/srne/srne-inv-hesp-20kw.webp',
    ARRAY['inverter', 'srne', '20kw', 'hesp', 'ip65', 'three-phase', 'hybrid'],
    '{"Rated AC Output":"20,000W (20kW) 3-Phase","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"350A","MPPT Voltage Range":"160 ~ 800V / 160 ~ 800V","Protection":"IP65 Waterproof","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000112',
    'SRNE 63A Three-Phase Automatic Transfer Switch Box (ATS380S63-S3)',
    'Inverters',
    'SRNE Accessories',
    'Automatic Transfer Switch (ATS) smart box for SRNE three-phase solar systems. Supports 380V/400V/415V AC grids with 63A nominal current and 2 system connections.',
    ARRAY['Rated 3-phase AC voltage: 380V, 400V, 415V (342V ~ 440V range)', '63A nominal input current handling', 'Automated source switching between grid, inverter, and generator', 'Supports 2 system connections', '2-Year official manufacturer warranty'],
    'Three-phase commercial and residential solar automatic power cutover',
    '₦535,000',
    'mid',
    true,
    '/products/srne/srne-acc-ats380s63.webp',
    ARRAY['ats', 'switch', 'three-phase', 'srne', 'accessory', 'automatic transfer'],
    '{"Phase":"3-Phase","Rated AC Voltage":"380V / 400V / 415V (342 ~ 440V)","Nominal Current":"63A","Max Connections":"2 Connections","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000113',
    'SRNE 12kW High-Voltage 300V Three-Phase Hybrid Inverter (HESP120SH3)',
    'Inverters',
    'SRNE HESP Series',
    'High-voltage three-phase 12kW 300V hybrid solar inverter with dual MPPT (16A+16A), 650Vdc maximum PV open circuit voltage, IP65 waterproof housing, and 5-year warranty.',
    ARRAY['12,000W continuous 3-phase high-voltage hybrid output', 'High-voltage 300V battery interface for ultra-low cable losses', 'Dual MPPT solar charge controller (16A + 16A)', '650Vdc maximum PV open circuit voltage rating', 'IP65 waterproof protection for harsh environments', '5-Year official manufacturer warranty'],
    'Modern high-voltage residential and light commercial three-phase solar installations',
    '₦2,276,000',
    'premium',
    true,
    '/products/srne/srne-inv-hesp-12kw-hv.webp',
    ARRAY['inverter', 'srne', '12kw', 'high-voltage', 'three-phase', 'hesp', 'hybrid'],
    '{"Rated AC Output":"12,000W (12kW) 3-Phase","Battery Voltage":"300V High Voltage","MPPT Charge Trackers":"16A + 16A","Max PV Voltage":"650Vdc","Protection":"IP65 Waterproof","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000082',
    'SRNE 6kW 48V Grid & Off-Grid Hybrid Inverter (HESP4860S100-H)',
    'Inverters',
    'SRNE HESP Series',
    'Grid-tied and off-grid hybrid inverter with dual-mode energy management, 100A MPPT charger, 500Vdc PV open circuit rating, waterproof casing, and 5-year official warranty.',
    ARRAY['6,000W continuous grid-interactive and pure off-grid bidirectional operation', '100A MPPT solar charging with peak shaving & export control', '500Vdc maximum PV open circuit voltage', 'Parallels up to 6 units for large multi-kilowatt systems', 'Waterproof outdoor build with 5-year official warranty'],
    'Hybrid solar homes seeking grid-feed and total energy autonomy',
    '₦1,058,000',
    'premium',
    true,
    '/products/srne/srne-inv-hesp-6kw.webp',
    ARRAY['inverter', 'srne', '6kw', 'grid-tied', 'hesp', 'hybrid', 'parallel'],
    '{"Rated AC Output":"6,000W Grid & Off-Grid","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"100A","Max PV Input":"500Vdc","Parallel Capability":"Up to 6 units","Protection":"Waterproof / IP65","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000115',
    'SRNE 12kW 48V Single-Phase Hybrid Inverter (HESP48120S200-H)',
    'Inverters',
    'SRNE HESP Series',
    'High-capacity 12kW 48V single-phase grid & off-grid hybrid inverter with large 200A MPPT charge controller, 500Vdc PV input, waterproof casing, and 5-year warranty.',
    ARRAY['12,000W heavy-duty single-phase pure sine wave hybrid output', '200A high-speed MPPT solar charging capacity', '500Vdc maximum PV open circuit voltage', 'Grid feedback, peak-shaving, and generator auto-start compatibility', 'Waterproof chassis with 5-year manufacturer warranty'],
    'Executive duplexes, heavy single-phase air conditioning loads, and offices',
    '₦2,331,000',
    'premium',
    true,
    '/products/srne/srne-inv-hesp-12kw.webp',
    ARRAY['inverter', 'srne', '12kw', 'single-phase', 'hesp', 'hybrid', '200a'],
    '{"Rated AC Output":"12,000W (12kW) Single-Phase","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"200A","Max PV Open Circuit Voltage":"500Vdc","Protection":"Waterproof / IP65","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000116',
    'SRNE 12kW 48V Three-Phase Hybrid Inverter (HESP48120SH3)',
    'Inverters',
    'SRNE HESP Series',
    'Industrial-grade 12kW 48V three-phase hybrid inverter with massive 260A MPPT solar charging, 650Vdc PV input, IP65 waterproof outdoor enclosure, and 5-year warranty.',
    ARRAY['12,000W continuous 3-phase hybrid grid-tied & off-grid operation', '260A MPPT high-current solar charge controller', '650Vdc high-voltage PV open circuit design', 'IP65 waterproof and dustproof for exterior wall mounting', '5-Year manufacturer replacement warranty'],
    'Commercial buildings, 3-phase workshops, and large residential estates',
    '₦2,422,000',
    'premium',
    true,
    '/products/srne/srne-inv-hesp-12kw-3p.webp',
    ARRAY['inverter', 'srne', '12kw', 'three-phase', 'hesp', 'hybrid', 'ip65'],
    '{"Rated AC Output":"12,000W (12kW) 3-Phase","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"260A","Max PV Open Circuit Voltage":"650Vdc","Protection":"IP65 Waterproof","Warranty":"5-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000085',
    'SRNE 16kW 48V Hybrid Inverter Charger (ASP48160S300-H)',
    'Inverters',
    'SRNE ASP Series',
    'High-power 16kW 48V grid and off-grid hybrid inverter charger with 300A MPPT solar charging, 650Vdc PV input, and parallel scalability up to 6 units.',
    ARRAY['16,000W continuous heavy-duty AC output', '300A high-capacity MPPT solar charger', '650Vdc high-voltage PV open circuit capability', 'Parallels up to 6 units (up to 96kW total capacity)', '2-Year official manufacturer warranty'],
    'High-draw commercial installations, manufacturing workshops, and mini-grids',
    '₦2,282,000',
    'premium',
    true,
    '/products/srne/srne-inv-asp-16kw.webp',
    ARRAY['inverter', 'srne', '16kw', '300a', 'asp', 'industrial', 'solar', 'parallel'],
    '{"Rated AC Output":"16,000W","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"300A","Max PV Open Circuit Voltage":"650Vdc","Parallel Capability":"Up to 6 units","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000083',
    'SRNE 10kW 48V Grid & Off-Grid Hybrid Inverter (ASP48100S200-H)',
    'Inverters',
    'SRNE ASP Series',
    '10kW 48V grid & off-grid hybrid inverter charger with 200A MPPT charger, 500Vdc PV input, and parallel capability up to 6 units.',
    ARRAY['10,000W continuous pure sine wave output', '200A integrated MPPT solar charge controller', '500Vdc maximum PV open circuit voltage', 'Parallels up to 6 units for up to 60kW system capacity', '2-Year official manufacturer warranty'],
    'Commercial offices, large homes, and commercial backup setups',
    '₦1,203,000',
    'mid',
    true,
    '/products/srne/srne-inv-asp-10kw.webp',
    ARRAY['inverter', 'srne', '10kw', 'asp', 'commercial', 'solar', 'parallel'],
    '{"Rated AC Output":"10,000W","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"200A","Max PV Input":"500Vdc","Parallel Capability":"Up to 6 units","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000084',
    'SRNE 12kW 48V Grid & Off-Grid Hybrid Inverter (ASP48120S200-H)',
    'Inverters',
    'SRNE ASP Series',
    'Heavy-duty 12kW 48V grid & off-grid hybrid inverter charger with 200A MPPT charge controller, 500Vdc PV input, and parallel scaling up to 6 units.',
    ARRAY['12,000W continuous pure sine wave AC output', '200A MPPT solar charging capacity', '500Vdc maximum PV open circuit voltage', 'Parallels up to 6 units (up to 72kW total)', '2-Year official manufacturer warranty'],
    'Large homes with multiple inverter ACs and commercial spaces',
    '₦1,280,000',
    'premium',
    true,
    '/products/srne/srne-inv-asp-12kw.webp',
    ARRAY['inverter', 'srne', '12kw', 'asp', 'heavy-duty', 'solar', 'parallel'],
    '{"Rated AC Output":"12,000W","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"200A","Max PV Input":"500Vdc","Parallel Capability":"Up to 6 units","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000120',
    'SRNE 12kW 48V Three-Phase MPPT Inverter Charger (ASP48120SH3)',
    'Inverters',
    'SRNE ASP Series',
    'Three-phase 12kW 48V inverter charger featuring 260A MPPT solar charging, 650Vdc maximum PV open circuit rating, and robust industrial power delivery.',
    ARRAY['12,000W continuous 3-phase AC power delivery', '260A MPPT high-efficiency solar charger', '650Vdc maximum PV open circuit voltage', 'Industrial surge handling with DSP electronic controls', '2-Year official manufacturer warranty'],
    'Three-phase commercial facilities, workshops, and light industrial sites',
    '₦1,321,000',
    'mid',
    true,
    '/products/srne/srne-inv-asp-12kw-3p.webp',
    ARRAY['inverter', 'srne', '12kw', 'three-phase', 'asp', 'solar', 'mppt'],
    '{"Rated AC Output":"12,000W (12kW) 3-Phase","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"260A","Max PV Input Voltage":"650Vdc","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000121',
    'SRNE Solarman WiFi Monitoring Kit (WF-1 Module)',
    'Inverters',
    'SRNE Accessories',
    'Plug-and-play Solarman WiFi communication module compatible with all SRNE hybrid and off-grid inverter models for real-time mobile app and web telemetry.',
    ARRAY['Compatible with all SRNE inverter series (HESP, ASP, AFP, AEP, HF)', 'Real-time solar generation, battery SOC, and power flow telemetry', 'Solarman Smart App and web browser dashboard access', 'Remote firmware diagnostics and parameter adjustments', '1-Year official manufacturer warranty'],
    'Remote monitoring and tracking of any SRNE solar installation',
    '₦55,000',
    'affordable',
    true,
    '/products/srne/srne-acc-solarman-wifi.webp',
    ARRAY['wifi', 'monitoring', 'solarman', 'srne', 'accessory', 'module'],
    '{"Compatibility":"All SRNE Inverter Models","Communication":"WiFi 802.11 b/g/n / RS485 / USB","Telemetry":"Solarman Smart / SRNE Cloud","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
),
(
    'a0000000-0000-0000-0000-000000000122',
    'SRNE 800A Low-Voltage Battery Busbar Box 4-In 4-Out (DCB-1)',
    'Batteries',
    'SRNE Accessories',
    'Engineered low-voltage DC battery busbar junction box supporting 4-in / 4-out connections, 800A nominal current, and up to 40.96kW total power handling.',
    ARRAY['4-In / 4-Out heavy-duty DC connection ports', '800A nominal DC current carrying capacity', '40.96kW maximum power throughput', 'Safe, organized parallel connection for multiple 48V battery racks', '1-Year official manufacturer warranty'],
    'Paralleling multiple 48V lithium battery banks safely in large residential & commercial setups',
    '₦117,000',
    'mid',
    true,
    '/products/srne/srne-acc-dcb1.webp',
    ARRAY['busbar', 'dcb', 'srne', 'battery box', 'accessory', '48v'],
    '{"Configuration":"4 In / 4 Out","Nominal Current":"800A","Max Power":"40.96kW","Voltage Class":"Low Voltage 48Vdc","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
),
(
    'a0000000-0000-0000-0000-000000000123',
    'SRNE 300A Low-Voltage Battery Busbar Box 2-In 2-Out (DCB-2)',
    'Batteries',
    'SRNE Accessories',
    'Compact low-voltage DC battery busbar junction box featuring 2-in / 2-out connections, 300A current rating, and 15.36kW maximum power handling.',
    ARRAY['2-In / 2-Out copper busbar terminals', '300A nominal DC current capacity', '15.36kW maximum power throughput', 'Clean, safe parallel combining for two 48V battery modules', '1-Year official manufacturer warranty'],
    'Dual battery setups in residential solar installations',
    '₦125,000',
    'mid',
    true,
    '/products/srne/srne-acc-dcb2.webp',
    ARRAY['busbar', 'dcb', 'srne', 'battery box', 'accessory', '48v'],
    '{"Configuration":"2 In / 2 Out","Nominal Current":"300A","Max Power":"15.36kW","Voltage Class":"Low Voltage 48Vdc","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
),
(
    'a0000000-0000-0000-0000-000000000124',
    'SRNE 1.5kW 1.28kWh All-In-One Solar Inverter & Lithium Battery System (EOT01S)',
    'Inverters',
    'SRNE EOT All-in-One Series',
    'Compact plug-and-play all-in-one solar energy system combining a 12V 1500W pure sine wave inverter charger with an internal 12.8V 100Ah (1.28kWh) LiFePO4 lithium battery.',
    ARRAY['1500W pure sine wave inverter and integrated solar charge controller', '1.28kWh internal LiFePO4 battery (12.8V / 100Ah)', 'All-in-one compact enclosure: zero external battery wiring needed', 'Seamless UPS switchover for electronics, TV, and workstations', '3-Year official manufacturer replacement warranty'],
    'Apartments, home workstations, POS terminals, and mobile off-grid setups',
    '₦753,000',
    'mid',
    true,
    '/products/srne/srne-aio-eot01s.webp',
    ARRAY['all-in-one', 'inverter', 'battery', 'srne', 'eot', '1.5kw', '1.28kwh'],
    '{"Inverter Rating":"12V / 1,500W Pure Sine Wave","Battery Capacity":"12.8V / 100Ah (1.28kWh LiFePO4)","Solar Charging":"Integrated MPPT Charger","Enclosure":"All-in-One Integrated Cabinet","Warranty":"3-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000125',
    'SRNE 2.5kW 2.56kWh All-In-One Solar Inverter & Lithium Battery System (EOT02S)',
    'Inverters',
    'SRNE EOT All-in-One Series',
    'Versatile all-in-one energy storage system integrating a 24V 2500W pure sine wave solar inverter charger and a built-in 25.6V 100Ah (2.56kWh) LiFePO4 battery pack.',
    ARRAY['2500W pure sine wave solar inverter charger', '2.56kWh built-in LiFePO4 storage capacity (25.6V / 100Ah)', 'Zero installation complexity: all-in-one integrated cabinet', 'Supports solar charging, generator input, and utility grid bypass', '3-Year official manufacturer replacement warranty'],
    '1-2 bedroom flats, medical clinics, offices, and small business backup',
    '₦987,000',
    'mid',
    true,
    '/products/srne/srne-aio-eot02s.webp',
    ARRAY['all-in-one', 'inverter', 'battery', 'srne', 'eot', '2.5kw', '2.56kwh'],
    '{"Inverter Rating":"24V / 2,500W Pure Sine Wave","Battery Capacity":"25.6V / 100Ah (2.56kWh LiFePO4)","Solar Charging":"Integrated MPPT Charger","Enclosure":"All-in-One Integrated Cabinet","Warranty":"3-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000090',
    'SRNE 2.56kWh 12V 200Ah LiFePO4 Lithium Battery (EOS02B-12)',
    'Batteries',
    'SRNE EOS Series',
    'Heavy-duty 12V 200Ah (2.56kWh) LiFePO4 lithium battery with 6,000+ deep cycles, internal intelligent BMS protection, and parallel scalability up to 4 units.',
    ARRAY['2,560Wh (2.56kWh) storage capacity at 12.8V nominal', '200Ah high-current discharge rating', '6,000+ cycles lifespan at 80% DoD', 'Parallels up to 4 units (10.24kWh total capacity)', '5-Year manufacturer replacement warranty'],
    '12V inverter setups, boats, caravans, security stations, and solar streetlights',
    '₦533,000',
    'mid',
    true,
    '/products/srne/srne-bat-eos02b-12.webp',
    ARRAY['battery', 'srne', '12v', '200ah', 'lifepo4', 'lithium', 'eos'],
    '{"Nominal Energy":"2.56kWh (2,560Wh)","Voltage / Capacity":"12.8V / 200Ah","Cycle Life":"6,000+ Cycles (80% DoD)","Parallel Limit":"Max 4 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000091',
    'SRNE 2.56kWh 24V 100Ah LiFePO4 Lithium Battery (EOS02B-24)',
    'Batteries',
    'SRNE EOS Series',
    'Compact 24V 100Ah (2.56kWh) LiFePO4 storage battery with 6,000 cycles life, precision BMS balancing, and support for up to 4 units in parallel.',
    ARRAY['2,560Wh (2.56kWh) energy capacity at 25.6V nominal', '100Ah discharge rate with ultra-low internal resistance', '6,000+ cycles lifespan at 80% DoD', 'Parallels up to 4 units (10.24kWh total capacity)', '5-Year manufacturer replacement warranty'],
    '24V inverter solar systems, residential backup, and office workstations',
    '₦630,000',
    'mid',
    true,
    '/products/srne/srne-bat-eos02b-24.webp',
    ARRAY['battery', 'srne', '24v', '100ah', 'lifepo4', 'lithium', 'eos'],
    '{"Nominal Energy":"2.56kWh (2,560Wh)","Voltage / Capacity":"25.6V / 100Ah","Cycle Life":"6,000+ Cycles (80% DoD)","Parallel Limit":"Max 4 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000092',
    'SRNE 7.16kWh 24V 280Ah LiFePO4 Lithium Battery (EOS08B-24)',
    'Batteries',
    'SRNE EOS Series',
    'High-capacity 24V 280Ah (7.16kWh) LiFePO4 storage battery with 6,000 deep cycles, high-rate discharge capability, and parallel support up to 4 units.',
    ARRAY['7,168Wh (7.16kWh) substantial storage capacity', '24V nominal (280Ah high capacity prismatic cells)', '6,000+ cycles lifespan at 80% DoD', 'Parallels up to 4 units (up to 28.6kWh capacity)', '5-Year manufacturer replacement warranty'],
    'High-demand 24V solar setups, small commercial stores, and homes',
    '₦1,348,000',
    'premium',
    true,
    '/products/srne/srne-bat-eos08b-24.webp',
    ARRAY['battery', 'srne', '24v', '280ah', '7kwh', 'lifepo4', 'eos'],
    '{"Nominal Energy":"7.16kWh (7,168Wh)","Voltage / Capacity":"25.6V / 280Ah","Cycle Life":"6,000+ Cycles (80% DoD)","Parallel Limit":"Max 4 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000093',
    'SRNE 5.12kWh 48V 100Ah Smart LiFePO4 Wall Battery (SE05B)',
    'Batteries',
    'SRNE SE Series',
    'Wall-mounted smart 5.12kWh 48V 100Ah LiFePO4 battery with integrated WiFi & Bluetooth telemetry, 6,000 cycles, and parallel scaling up to 16 units (81.92kWh).',
    ARRAY['5.12kWh rated energy at 51.2V / 100Ah', 'Integrated WiFi & Bluetooth for live mobile app monitoring', '6,000 cycles lifespan at 80% DoD', 'Parallels up to 16 units for massive 81.92kWh scalable storage', '5-Year manufacturer replacement warranty'],
    'Modern residential homes, wall installations, and multi-battery setups',
    '₦1,002,000',
    'premium',
    true,
    '/products/srne/srne-bat-se05b-wall.webp',
    ARRAY['battery', 'srne', '48v', '5kwh', 'wifi', 'bluetooth', 'lifepo4', 'se'],
    '{"Nominal Energy":"5.12kWh (5,120Wh)","Voltage / Capacity":"51.2V / 100Ah","Connectivity":"WiFi & Bluetooth App Monitoring","Cycle Life":"6,000 Cycles","Parallel Capability":"Max 16 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000094',
    'SRNE 10.49kWh 48V 205Ah Smart LiFePO4 Powerwall Battery (SE10B)',
    'Batteries',
    'SRNE SE Series',
    'Sleek wall-mounted 10.49kWh 48V 205Ah LiFePO4 powerwall battery with wireless WiFi & Bluetooth telemetry, 6,000 cycles lifespan, and parallel scaling up to 16 units.',
    ARRAY['10.49kWh high-density energy storage (51.2V / 205Ah)', 'Built-in WiFi and Bluetooth for smartphone diagnostics', '6,000 cycles lifespan at 80% DoD', 'Parallels up to 16 units (up to 167.8kWh total capacity)', '5-Year manufacturer replacement warranty'],
    '3-5 bedroom homes, luxury apartments, and commercial facilities',
    '₦1,804,000',
    'premium',
    true,
    '/products/srne/srne-bat-se10b-wall.webp',
    ARRAY['battery', 'srne', '10kwh', '48v', 'powerwall', 'lifepo4', 'se'],
    '{"Nominal Energy":"10.49kWh","Voltage / Capacity":"51.2V / 205Ah","Connectivity":"WiFi & Bluetooth App Monitoring","Cycle Life":"6,000 Cycles","Parallel Capability":"Max 16 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000095',
    'SRNE 14.33kWh 48V 280Ah Smart LiFePO4 Storage Battery (SE15B)',
    'Batteries',
    'SRNE SE Series',
    'High-capacity 14.33kWh 48V 280Ah LiFePO4 energy storage battery with integrated WiFi & Bluetooth, 6,000 cycles lifespan, and parallel support up to 16 units (229.2kWh).',
    ARRAY['14.33kWh substantial storage capacity (51.2V / 280Ah)', 'Built-in WiFi & Bluetooth real-time monitoring', '6,000+ deep cycles lifespan', 'Parallels up to 16 units (up to 229.2kWh total capacity)', '5-Year manufacturer replacement warranty'],
    'Large residences, private clinics, commercial buildings, and off-grid villas',
    '₦2,316,000',
    'premium',
    true,
    '/products/srne/srne-bat-se15b-tower.webp',
    ARRAY['battery', 'srne', '14kwh', '48v', '280ah', 'commercial', 'lifepo4', 'se'],
    '{"Nominal Energy":"14.33kWh","Voltage / Capacity":"51.2V / 280Ah","Connectivity":"WiFi & Bluetooth Monitoring","Cycle Life":"6,000 Cycles","Parallel Capability":"Max 16 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000096',
    'SRNE 16.07kWh 51.2V 314Ah LCD LiFePO4 Roller Battery (SE16B-Pro)',
    'Batteries',
    'SRNE Pro Series',
    'Premium mobile 16.07kWh 51.2V 314Ah LiFePO4 roller storage battery featuring an interactive LCD screen, WiFi & Bluetooth telemetry, heavy-duty casters, and 6,000 cycles lifespan.',
    ARRAY['16.07kWh massive capacity with 314Ah grade-A cells', 'High-contrast LCD control screen for instant voltage, current, and SOC data', 'Built-in WiFi and Bluetooth wireless app connectivity', 'Heavy-duty mobile roller chassis for effortless positioning', 'Parallels up to 16 units (up to 257.1kWh total)', '5-Year official manufacturer warranty'],
    'Executive residences, data centers, hotels, and luxury solar setups',
    '₦2,502,000',
    'premium',
    true,
    '/products/srne/srne-bat-se16b-pro.webp',
    ARRAY['battery', 'srne', '16kwh', '314ah', 'lcd', 'roller', 'pro', 'lifepo4'],
    '{"Nominal Energy":"16.07kWh (16,070Wh)","Voltage / Capacity":"51.2V / 314Ah","Display":"Front-Panel Interactive LCD Screen","Connectivity":"WiFi & Bluetooth","Cycle Life":"6,000 Cycles","Parallel Capability":"Max 16 units in parallel","Warranty":"5-Year Manufacturer Warranty"}'::jsonb,
    25,
    60
),
(
    'a0000000-0000-0000-0000-000000000097',
    'SRNE 5.12kWh 51.2V 100Ah 10-Year Warranty LiFePO4 Battery (EOS05B-Pro)',
    'Batteries',
    'SRNE EOS Pro Series',
    'Professional-grade 5.12kWh 51.2V 100Ah LiFePO4 lithium battery backed by an industry-leading 10-year official warranty, 6,000 cycles, and parallel scalability up to 16 units.',
    ARRAY['5.12kWh rated capacity at 51.2V / 100Ah', 'Industry-leading 10-Year manufacturer replacement warranty', '6,000+ deep cycles lifespan (80% DoD, 0.5C, 25°C)', 'Support max 16pcs in parallel (up to 81.92kWh)', 'CAN / RS485 communication with Deye, SRNE, and leading inverters'],
    'Long-term home solar investments requiring maximum warranty protection',
    '₦1,219,000',
    'premium',
    true,
    '/products/srne/srne-bat-eos05b-pro.webp',
    ARRAY['battery', 'srne', '5kwh', '10-year warranty', 'eos pro', 'lifepo4'],
    '{"Nominal Energy":"5.12kWh","Voltage / Capacity":"51.2V / 100Ah","Cycle Life":"6,000 Cycles (80% DoD, 0.5C)","Parallel Capability":"Max 16 units (81.92kWh)","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000098',
    'SRNE 10.24kWh 51.2V 200Ah 10-Year Warranty LiFePO4 Battery (EOS10B)',
    'Batteries',
    'SRNE EOS Pro Series',
    'Premium 10.24kWh 51.2V 200Ah LiFePO4 lithium battery with 10-year official warranty, 6,000 cycles, and support for up to 16 units in parallel (163.84kWh).',
    ARRAY['10.24kWh substantial capacity (51.2V / 200Ah)', '10-Year official manufacturer replacement warranty', '6,000+ deep cycles lifespan (80% DoD, 0.5C, 25°C)', 'Support max 16pcs in parallel of 163.84kWh total capacity', 'Dual BMS communication ports with automated address assignment'],
    'Executive residences, duplexes, and commercial solar installations',
    '₦2,672,000',
    'premium',
    true,
    '/products/srne/srne-bat-eos10b-pro.webp',
    ARRAY['battery', 'srne', '10kwh', '200ah', '10-year warranty', 'eos10b', 'lifepo4'],
    '{"Nominal Energy":"10.24kWh","Voltage / Capacity":"51.2V / 200Ah","Cycle Life":"6,000 Cycles (80% DoD, 0.5C)","Parallel Capability":"Max 16 units (163.84kWh)","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000099',
    'SRNE 16.07kWh 51.2V 314Ah IP65 10-Year Warranty Battery (EOS15B)',
    'Batteries',
    'SRNE EOS Pro Series',
    'High-capacity IP65 waterproof 16.07kWh 51.2V 314Ah LiFePO4 battery with 8,000 deep cycles, 10-year warranty, and parallel scaling up to 16 units (257.12kWh).',
    ARRAY['16.07kWh high energy density (51.2V / 314Ah)', '8,000 deep cycles lifespan (80% DoD, 0.5C, 25°C)', 'IP65 protection grade for demanding exterior or indoor environments', 'Support max 16pcs in parallel of 257.12kWh', '10-Year official manufacturer replacement warranty'],
    'Commercial buildings, industrial sites, hotels, and luxury estate power backup',
    '₦3,034,000',
    'premium',
    true,
    '/products/srne/srne-bat-eos15b-pro.webp',
    ARRAY['battery', 'srne', '16kwh', 'ip65', '8000 cycles', '10-year warranty', 'eos15b'],
    '{"Nominal Energy":"16.07kWh","Voltage / Capacity":"51.2V / 314Ah","Cycle Life":"8,000 Cycles (80% DoD, 0.5C)","Protection Grade":"IP65 Waterproof","Parallel Capability":"Max 16 units (257.12kWh)","Warranty":"10-Year Official Manufacturer Warranty"}'::jsonb,
    25,
    120
),
(
    'a0000000-0000-0000-0000-000000000136',
    'SRNE 1.5kW 12V MPPT Solar Charge Inverter (HF1215S60-108)',
    'Inverters',
    'SRNE HF Series',
    'Compact 1.5kW 12V pure sine wave solar charge inverter with integrated 60A MPPT charge controller and 100Vdc maximum PV open circuit voltage.',
    ARRAY['1,500W pure sine wave continuous output', '60A integrated MPPT solar charger', '100Vdc maximum PV open circuit voltage', 'Low idle consumption with smart battery charging profile', '2-Year official manufacturer warranty'],
    'Small apartments, studios, security booths, and mobile power setups',
    '₦266,000',
    'affordable',
    true,
    '/products/srne/srne-inv-hf-1.5kw.webp',
    ARRAY['inverter', 'srne', '1.5kw', '12v', 'hf', 'mppt', 'affordable'],
    '{"Rated AC Output":"1,500W Pure Sine Wave","Nominal DC Voltage":"12Vdc","MPPT Charge Current":"60A","Max PV Open Circuit Voltage":"100Vdc","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000137',
    'SRNE 3kW 24V MPPT Solar Charge Inverter (HF2430S60-108)',
    'Inverters',
    'SRNE HF Series',
    'Promotion price 3kW 24V pure sine wave solar charge inverter with 60A MPPT charge controller and 100Vdc maximum PV open circuit voltage.',
    ARRAY['3,000W continuous pure sine wave power', '60A MPPT solar charge controller', '100Vdc maximum PV open circuit voltage', 'Special promotional price for high-value residential solar', '2-Year official manufacturer warranty'],
    '2-3 bedroom homes, flats, offices, and small business setups',
    '₦249,000',
    'affordable',
    true,
    '/products/srne/srne-inv-hf-3kw.webp',
    ARRAY['inverter', 'srne', '3kw', '24v', 'hf', 'mppt', 'promotion'],
    '{"Rated AC Output":"3,000W Pure Sine Wave","Nominal DC Voltage":"24Vdc","MPPT Charge Current":"60A","Max PV Open Circuit Voltage":"100Vdc","Special":"Promotion Price","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000138',
    'SRNE 3.3kW 24V High-Voltage MPPT Solar Inverter (HF2430S80-H)',
    'Inverters',
    'SRNE HF Series',
    'Enhanced 3.3kW 24V solar charge inverter featuring an 80A MPPT charge controller and 500Vdc high-voltage PV open circuit input for series solar arrays.',
    ARRAY['3,300W pure sine wave continuous output', '80A high-capacity MPPT solar charger', '500Vdc high-voltage PV input allows longer panel strings', 'Multi-stage charging for LiFePO4, AGM, and Gel batteries', '2-Year official manufacturer warranty'],
    'Residential homes wanting high PV voltage string efficiency with a 24V battery',
    '₦374,000',
    'mid',
    true,
    '/products/srne/srne-inv-hf-3.3kw.webp',
    ARRAY['inverter', 'srne', '3.3kw', '24v', 'hf', '500vdc', 'mppt'],
    '{"Rated AC Output":"3,300W Pure Sine Wave","Nominal DC Voltage":"24Vdc","MPPT Charge Current":"80A","Max PV Open Circuit Voltage":"500Vdc","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000004',
    'SRNE 5kW 48V Parallel Solar Charge Inverter (HFP4850S80-145)',
    'Inverters',
    'SRNE HF Series',
    'Promotion price 5kW 48V parallel solar charge inverter with 80A MPPT charge controller, 145Vdc maximum PV open circuit voltage, and parallel support up to 6 units.',
    ARRAY['5,000W continuous output / 10,000W motor surge', 'Integrated 80A MPPT solar charge controller', '145Vdc maximum PV open circuit voltage', 'Supports parallel operation up to 6 units (30kW total)', 'Special promotion price with 2-year official warranty'],
    'Residential backup, parallel scalable solar setups, and budget-conscious solar homes',
    '₦369,000',
    'mid',
    true,
    '/products/srne/srne-inv-hfp-5kw.webp',
    ARRAY['inverter', 'srne', '5kw', 'parallel', 'hfp', 'promotion', 'solar'],
    '{"Rated AC Output":"5,000W Pure Sine Wave","Nominal DC Voltage":"48Vdc","MPPT Charge Current":"80A","Max PV Open Circuit Voltage":"145Vdc","Parallel Capability":"Up to 6 units","Special":"Promotion Price","Warranty":"2-Year Manufacturer Warranty"}'::jsonb,
    25,
    24
),
(
    'a0000000-0000-0000-0000-000000000140',
    'SRNE 40A 12V/24V PWM Solar Charge Controller (HC2440)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'Reliable 40A 12V/24V auto-sensing PWM solar charge controller with 55V maximum PV input voltage, dual USB charging ports, and multi-stage battery charging logic.',
    ARRAY['40A continuous charge rating with 12V/24V auto recognition', '55V maximum PV input voltage', 'LCD display showing battery level, solar current, and load status', 'Built-in electronic protections (overload, short circuit, reverse polarity)', '1-Year official manufacturer warranty'],
    'Entry-level solar lighting, cabins, RVs, telecommunication poles, and small DC systems',
    '₦29,000',
    'entry',
    true,
    '/products/srne/srne-scc-hc2440.webp',
    ARRAY['controller', 'pwm', 'srne', '40a', 'hc', 'solar charger'],
    '{"Type":"PWM Solar Controller","Rated Current":"40A","System Voltage":"12V / 24V Auto","Max PV Input Voltage":"55V","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
),
(
    'a0000000-0000-0000-0000-000000000141',
    'SRNE 60A 12V/24V PWM Solar Charge Controller (HC2460)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'High-current 60A 12V/24V PWM solar charge controller with 55V maximum PV input voltage, illuminated LCD screen, and heavy-duty screw terminals.',
    ARRAY['60A continuous solar charging current', '12V/24V automatic voltage detection', '55V maximum PV input voltage', 'Dual USB 5V/2A outputs and programmable load control', '1-Year official manufacturer warranty'],
    'Budget solar setups, streetlights, DC solar water pumps, and remote farm lighting',
    '₦52,000',
    'affordable',
    true,
    '/products/srne/srne-scc-hc2460.webp',
    ARRAY['controller', 'pwm', 'srne', '60a', 'hc', 'solar charger'],
    '{"Type":"PWM Solar Controller","Rated Current":"60A","System Voltage":"12V / 24V Auto","Max PV Input Voltage":"55V","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
),
(
    'a0000000-0000-0000-0000-000000000142',
    'SRNE Shiner 30A 12V/24V MPPT Solar Charge Controller (Shiner2430)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'High-efficiency 30A MPPT solar charge controller with 100V maximum input voltage, rear aluminum heat sink design for passive silent cooling, and 99% tracking efficiency.',
    ARRAY['30A MPPT charging current with 12V/24V auto detection', '100V maximum PV input voltage', 'Rear aluminum heat sink design for fanless, silent natural cooling', 'Up to 99.9% MPPT tracking efficiency', '3-Year official manufacturer warranty'],
    'Residential 12V/24V solar systems, campervans, and silent indoor installations',
    '₦52,000',
    'mid',
    true,
    '/products/srne/srne-scc-shiner2430.webp',
    ARRAY['controller', 'mppt', 'srne', '30a', 'shiner', 'solar charger'],
    '{"Type":"MPPT Solar Controller","Rated Current":"30A","System Voltage":"12V / 24V Auto","Max PV Input Voltage":"100V","Cooling":"Rear Heat Sink Design","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000143',
    'SRNE Shiner 40A 12V/24V MPPT Solar Charge Controller (Shiner2440)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'Promotion price 40A MPPT solar charge controller with 100V maximum input voltage, rear heat sink passive cooling, and 99.9% peak tracking efficiency.',
    ARRAY['40A continuous MPPT charge current', '100V maximum PV input voltage', 'Rear heat sink design for silent, reliable convective cooling', 'Promotion price with 3-year official warranty', 'Bluetooth / RS485 communication for app data tracking'],
    'Residential 12V/24V solar power setups requiring high efficiency at great value',
    '₦52,000',
    'mid',
    true,
    '/products/srne/srne-scc-shiner2440.webp',
    ARRAY['controller', 'mppt', 'srne', '40a', 'shiner', 'promotion'],
    '{"Type":"MPPT Solar Controller","Rated Current":"40A","System Voltage":"12V / 24V Auto","Max PV Input Voltage":"100V","Cooling":"Rear Heat Sink Design","Special":"Promotion Price","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000144',
    'SRNE Shiner 60A 12V/24V MPPT Solar Charge Controller (Shiner2460)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'High-capacity 60A MPPT solar charge controller with 100V maximum input voltage, rear aluminum heat sink passive cooling, and promotional pricing.',
    ARRAY['60A heavy-duty continuous MPPT charging current', '100V maximum PV open circuit voltage', 'Rear heat sink cooling: zero fan noise, maintenance-free operation', 'Promotion price with 3-year official warranty', 'Multi-stage charging algorithm compatible with LiFePO4 and lead-acid'],
    'Larger 12V/24V solar battery setups, boats, and rural off-grid homesteads',
    '₦70,000',
    'mid',
    true,
    '/products/srne/srne-scc-shiner2460.webp',
    ARRAY['controller', 'mppt', 'srne', '60a', 'shiner', 'promotion'],
    '{"Type":"MPPT Solar Controller","Rated Current":"60A","System Voltage":"12V / 24V Auto","Max PV Input Voltage":"100V","Cooling":"Rear Heat Sink Design","Special":"Promotion Price","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000145',
    'SRNE 60A 12V/24V/36V/48V MPPT Solar Charge Controller (MF4860N15)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'Multi-voltage 60A MPPT solar charge controller supporting 12V, 24V, 36V, and 48V battery systems with 145Vdc maximum input voltage and active fan cooling.',
    ARRAY['60A MPPT charge current across 12V / 24V / 36V / 48V auto systems', '145Vdc maximum PV open circuit voltage', 'Intelligent temperature-controlled fan cooling', 'Promotion price with 3-year official manufacturer warranty', 'Full digital control with live LCD diagnostic display'],
    '48V residential battery setups, commercial solar arrays, and telecom stations',
    '₦102,000',
    'mid',
    true,
    '/products/srne/srne-scc-mf4860n15.webp',
    ARRAY['controller', 'mppt', 'srne', '60a', '48v', 'mf', 'promotion'],
    '{"Type":"MPPT Solar Controller","Rated Current":"60A","Battery Voltage":"12V / 24V / 36V / 48V Auto","Max PV Input Voltage":"145Vdc","Cooling":"Fan Cooling","Special":"Promotion Price","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000146',
    'SRNE 100A 12V/24V/36V/48V MPPT Solar Charge Controller (MC48100N25)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'Heavy-duty 100A universal MPPT solar charge controller for 12V/24V/36V/48V systems featuring 250V maximum input voltage and high-efficiency rear heat sink cooling.',
    ARRAY['100A massive continuous MPPT charging current', 'Universal 12V / 24V / 36V / 48V auto battery detection', '250V maximum PV open circuit voltage for high-voltage panel strings', 'Heavy-duty heat sink design at the back for silent, reliable cooling', '3-Year official manufacturer warranty'],
    'High-capacity 48V solar battery banks and demanding commercial solar projects',
    '₦437,000',
    'premium',
    true,
    '/products/srne/srne-scc-mc48100n25.webp',
    ARRAY['controller', 'mppt', 'srne', '100a', '48v', 'mc', '250v'],
    '{"Type":"MPPT Solar Controller","Rated Current":"100A","Battery Voltage":"12V / 24V / 36V / 48V Auto","Max PV Input Voltage":"250V","Cooling":"Heat Sink Design at Back","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000147',
    'SRNE Dual MPPT 100A 48V Solar Charge Controller (MF48100N50)',
    'Inverters',
    'SRNE Solar Charge Controllers',
    'Enterprise-tier 48V 100A solar charge controller with 2 independent MPPT trackers, 500Vdc + 500Vdc maximum open circuit voltage, parallel support up to 16 units, and fan cooling.',
    ARRAY['100A continuous charging at 48Vdc nominal', '2 independent MPPT trackers with 500Vdc + 500Vdc max open circuit rating', 'Supports parallel operation up to 16 units for massive solar arrays', 'Smart fan cooling with real-time temperature telemetry', '3-Year official manufacturer warranty'],
    'Multi-string solar arrays, commercial mini-grids, and large 48V storage setups',
    '₦534,000',
    'premium',
    true,
    '/products/srne/srne-scc-mf48100n50.webp',
    ARRAY['controller', 'dual mppt', 'srne', '100a', '48v', 'mf', '500vdc', 'parallel'],
    '{"Type":"Dual MPPT Solar Controller","Rated Current":"100A","Nominal Voltage":"48Vdc","MPPT Trackers":"2 Trackers","Max Open Circuit Voltage":"500Vdc + 500Vdc","Parallel Limit":"Up to 16 units in parallel","Cooling":"Fan Cooling","Warranty":"3-Year Official Warranty"}'::jsonb,
    25,
    36
),
(
    'a0000000-0000-0000-0000-000000000148',
    'SRNE EOS05B Heavy-Duty Parallel Battery Cable Set',
    'Batteries',
    'SRNE Accessories',
    'Heavy-duty pure copper parallel power and communication cable set designed for linking SRNE EOS05B and EOS Pro lithium battery modules safely in parallel.',
    ARRAY['Ultra-low resistance pure copper multi-strand conductors', 'High-current flame-retardant quick-locking power connectors', 'RJ45 / CAN-bus communication link cable included', 'Precision-matched for SRNE EOS05B & EOS Pro series battery modules', '1-Year official manufacturer warranty'],
    'Interconnecting multiple SRNE EOS lithium batteries in parallel',
    '₦53,000',
    'affordable',
    true,
    '/products/srne/srne-acc-eos05b-cable.webp',
    ARRAY['cable', 'parallel cable', 'srne', 'eos05b', 'accessory', 'battery cable'],
    '{"Compatibility":"SRNE EOS05B, EOS10B, EOS15B Batteries","Conductor":"High-purity Oxygen-free Copper","Cable Type":"DC Power + BMS Communication Interconnect","Warranty":"1-Year Official Warranty"}'::jsonb,
    25,
    12
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    series = EXCLUDED.series,
    description = EXCLUDED.description,
    features = EXCLUDED.features,
    best_for = EXCLUDED.best_for,
    price = EXCLUDED.price,
    tier = EXCLUDED.tier,
    is_active = true,
    image_url = EXCLUDED.image_url,
    tags = EXCLUDED.tags,
    specifications = EXCLUDED.specifications,
    warranty_months = EXCLUDED.warranty_months,
    updated_at = NOW();
