-- ==============================================================================
-- 005_seed_alpsolarr_catalog.sql
-- Complete catalog of authentic AlpSolarr, Taico, and Dawnice products from the
-- official AlpSolarr Installer & Product Price Lists with genuine product images
-- and full technical specifications.
-- ==============================================================================

INSERT INTO public.products (
    id,
    name,
    category,
    series,
    description,
    features,
    best_for,
    price,
    tier,
    is_active,
    image_url,
    tags,
    specifications,
    stock_qty,
    warranty_months
) VALUES
(
    'c0000000-0000-0000-0000-000000000001',
    'AlpSolarr Pulse S3 6kW Eco-Hybrid Inverter',
    'Inverters',
    'AlpSolarr Pulse Series',
    '6kW high-efficiency pure sine wave eco-hybrid solar inverter with dual MPPT tracker, rugged IP66 weatherproofing, and 5-Year replacement warranty. Supports up to 12,000W massive PV input with 99.9% MPPT efficiency and up to 6 units in parallel.',
    ARRAY['6kW continuous AC rated output with pure sine wave generation', 'Massive 12', '000W max solar PV input capacity with dual MPPT trackers (99.9% efficiency)', 'Rugged IP66 waterproof and dustproof outdoor rated enclosure', 'Seamless <4ms UPS automatic transfer switch (ATS)', 'Parallel scalability supporting up to 6 units (36kW system capacity)', 'Integrated Wi-Fi & Bluetooth monitoring with Ligoo Smart Cloud App', '5-Year Manufacturer Replacement Warranty'],
    '3-4 bedroom residences, duplexes, retail stores, modern executive homes',
    '₦864,000',
    'mid',
    true,
    '/products/alpsolar/alp-inv-pulse-s3-6kw.webp',
    ARRAY['inverter', 'hybrid inverter', 'alpsolarr', 'alpsolar', 'ligoo', 'pulse s3', '6kw', '48v', 'solar inverter'],
    '{"Model":"Pulse S3-6KW","Rated AC Output":"6,000W Continuous / 12,000W Surge","Battery Nominal Voltage":"48Vdc (40V - 60V Range)","Max Solar PV Input":"12,000W (Dual MPPT)","MPPT Voltage Range":"120V - 500Vdc","Protection Rating":"IP66 Weatherproof / Dustproof","Parallel Capability":"Up to 6 Units (Single & 3-Phase)","End User Price (1-10 Units)":"₦900,000","Installer Price (10-20 Units)":"₦864,000","Dealer Price (20-40 Units)":"₦780,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    25,
    60
),
(
    'c0000000-0000-0000-0000-000000000002',
    'AlpSolarr Pulse S2 11kW High-Yield Hybrid Inverter',
    'Inverters',
    'AlpSolarr Pulse Series',
    '11kW high-power hybrid solar inverter engineered for heavy-duty domestic, commercial, and light industrial power demands. Features dual MPPT trackers, intelligent dual AC load management, and parallel scalability up to 6 single-phase or 9 three-phase units.',
    ARRAY['11kW continuous AC output capacity with pure sine wave technology', 'Dual MPPT tracker architecture for multi-roof orientation maximum solar harvest', 'Dual AC output ports for smart sub-load shedding and critical load prioritization', 'Supports parallel operation up to 6 units (66kW) or 9 units for 3-phase commercial (99kW)', 'Compatible with lithium (CAN/RS485 BMS) and lead-acid/GEL battery chemistries', 'High surge tolerance handling up to 22', '000W inductive motor startup surges', '2-Year Manufacturer Replacement Warranty'],
    'Large homes, commercial offices, hospitals, hotels, schools, workshops',
    '₦1,260,000',
    'premium',
    true,
    '/products/alpsolar/alp-inv-pulse-s2-11kw.webp',
    ARRAY['inverter', 'hybrid inverter', 'alpsolarr', 'alpsolar', 'pulse s2', '11kw', '48v', 'commercial solar'],
    '{"Model":"Pulse S2-11KW","Rated AC Output":"11,000W Continuous / 22,000W Surge","Battery Nominal Voltage":"48Vdc (40V - 60V Range)","Max Solar PV Input":"11,000W (Dual MPPT)","MPPT Voltage Range":"90V - 450Vdc","AC Outputs":"Dual AC Ports (Main + Smart Sub-Load)","Parallel Scalability":"Up to 6 Units Single Phase / 9 Units 3-Phase","End User Price (1-10 Units)":"₦1,380,000","Installer Price (10-20 Units)":"₦1,260,000","Dealer Price (20-40 Units)":"₦1,140,000","Warranty":"2-Year Replacement Warranty"}'::jsonb,
    18,
    24
),
(
    'c0000000-0000-0000-0000-000000000003',
    'AlpSolarr Pulse S4 8kW Smart Hybrid Inverter',
    'Inverters',
    'AlpSolarr Pulse Series',
    '8kW next-generation smart hybrid inverter with IP66 all-weather protection, dual-channel PV input, dedicated diesel generator dry contact interface, and built-in Wi-Fi and Bluetooth cloud telemetry. Engineered for luxury estates and commercial facilities.',
    ARRAY['8', '000W continuous rated AC output with clean pure sine wave power', 'Rugged IP66 rating for outdoor installation in humid', 'dusty', 'and tropical environments', 'Dual-channel high-voltage MPPT inputs maximizing daytime solar generation', 'Integrated generator auto-start (dry contact) and smart peak-shaving', 'Seamless parallel stacking with automatic master-slave coordination', '5-Year Manufacturer Replacement Warranty'],
    '5-bedroom duplexes, executive residences, supermarkets, banking outlets',
    '₦876,000',
    'premium',
    true,
    '/products/alpsolar/alp-inv-pulse-s4-8kw.webp',
    ARRAY['inverter', 'hybrid inverter', 'alpsolarr', 'pulse s4', '8kw', '48v', 'ip66'],
    '{"Model":"Pulse S4-8KW","Rated AC Output":"8,000W Continuous / 16,000W Surge","Battery Nominal Voltage":"48Vdc (40V - 60V Range)","Max Solar PV Input":"10,000W (Dual Channel)","Protection Rating":"IP66 Weatherproof / Dustproof","Generator Integration":"Dedicated Auto-Start Dry Contact","Communication":"CAN / RS485 / Wi-Fi / Bluetooth","Installer Price":"₦876,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    20,
    60
),
(
    'c0000000-0000-0000-0000-000000000004',
    'AlpSolarr Pulse S4 Mini 5kW Eco-Hybrid Inverter',
    'Inverters',
    'AlpSolarr Pulse Series',
    'Compact 5kW eco-hybrid inverter designed for space-conscious residential homes and small office setups. Delivers ultra-quiet cooling, IP66 outdoor durability, and robust lithium battery BMS communications.',
    ARRAY['5', '000W continuous output with pure sine wave AC waveform', 'Ultra-compact footprint with IP66 weatherproofing', 'High-efficiency MPPT charge controller with 99% conversion efficiency', 'Direct plug-and-play BMS integration with AlpSolarr Livo and standard LiFePO4 batteries', '5-Year Manufacturer Replacement Warranty'],
    'Apartments, 2-3 bedroom residential homes, clinic power, boutique retail',
    '₦636,000',
    'affordable',
    true,
    '/products/alpsolar/alp-inv-pulse-s4-mini-5kw.webp',
    ARRAY['inverter', 'hybrid inverter', 'alpsolarr', 'pulse s4 mini', '5kw', '48v'],
    '{"Model":"Pulse S4 Mini-5KW","Rated AC Output":"5,000W Continuous","Battery Voltage":"48Vdc","Max Solar PV Input":"7,000W","Protection Rating":"IP66 Weatherproof","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    15,
    60
),
(
    'c0000000-0000-0000-0000-000000000005',
    'AlpSolarr ROSA G2 12kW Commercial Hybrid Inverter',
    'Inverters',
    'AlpSolarr Rosa Series',
    '12kW high-capacity commercial hybrid inverter engineered with IP66 all-weather housing, multi-MPPT high-voltage PV architecture, and high surge capability. Supports parallel stacking and micro-grid synchronization.',
    ARRAY['12', '000W continuous heavy-duty AC output capacity', 'IP66 rated cast aluminum chassis for maximum heat dissipation and long life', 'Dual high-voltage MPPT trackers supporting massive rooftop solar arrays up to 16', '000W', 'Full microgrid and generator synchronization capabilities', '5-Year Manufacturer Replacement Warranty'],
    'Commercial buildings, luxury mansions, mini-grids, event centers, factories',
    '₦3,180,000',
    'premium',
    true,
    '/products/alpsolar/alp-inv-rosa-g2-12kw.webp',
    ARRAY['inverter', 'commercial inverter', 'alpsolarr', 'rosa g2', '12kw', 'hybrid'],
    '{"Model":"ROSA G2-12KW","Rated AC Output":"12,000W Continuous / 24,000W Surge","Battery Nominal Voltage":"48Vdc (Low Voltage Architecture)","Max Solar PV Input":"16,000W","MPPT Voltage Range":"120V - 500Vdc","Protection Rating":"IP66 Weatherproof / Dustproof","End User Price (1-10 Units)":"₦3,300,000","Installer Price (10-20 Units)":"₦3,180,000","Dealer Price (20-40 Units)":"₦3,060,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    12,
    60
),
(
    'c0000000-0000-0000-0000-000000000006',
    'AlpSolarr ROSA T2 15kW Three-Phase Commercial Hybrid Inverter',
    'Inverters',
    'AlpSolarr Rosa Series',
    '15kW three-phase 380V/400V commercial hybrid inverter with dual high-voltage MPPTs, unbalanced load support per phase, and complete microgrid coordination. Built to withstand demanding African climate conditions with IP66 rating.',
    ARRAY['15kW continuous true three-phase 400V AC power delivery', '100% unbalanced three-phase load handling capability', 'IP66 weatherproof casing with industrial grade components', 'Multi-unit parallel operation for multi-megawatt commercial systems', '5-Year Manufacturer Replacement Warranty'],
    'Commercial complexes, hotels, fuel stations, factories, cold storage',
    '₦3,960,000',
    'premium',
    true,
    '/products/alpsolar/alp-inv-rosa-t2-15kw.webp',
    ARRAY['inverter', 'three phase', 'commercial inverter', 'alpsolarr', 'rosa t2', '15kw'],
    '{"Model":"ROSA T2-15KW","Rated AC Output":"15,000W Continuous (Three Phase 380V/400V)","Battery Nominal Voltage":"48Vdc Low Voltage Architecture","Max Solar PV Input":"20,000W (Dual MPPT)","Protection Rating":"IP66 Weatherproof","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    10,
    60
),
(
    'c0000000-0000-0000-0000-000000000007',
    'AlpSolarr Livo-Y 5.12kWh 51.2V (100Ah) LiFePO4 Lithium Battery',
    'Batteries',
    'AlpSolarr Livo Series',
    '5.12kWh 51.2V 100Ah automotive-grade LiFePO4 wall-mount energy storage battery. Features front status display, smart multi-protocol BMS (CAN/RS485), 6,000+ deep cycles, and a 5-Year replacement warranty. Seamlessly pairs with AlpSolarr Pulse and ROSA series inverters.',
    ARRAY['5.12kWh usable energy capacity with 51.2V nominal voltage (100Ah)', 'Premium Tier-1 LiFePO4 prismatic cells delivering over 6', '000 cycles at 80% DoD', 'Integrated smart BMS with overcharge', 'overdischarge', 'overcurrent', 'and thermal protection', 'Multi-brand protocol compatibility via CAN/RS485 (AlpSolarr', 'Deye', 'Luxpower', 'SRNE', 'Felicity)', 'Scalable parallel expansion supporting up to 15 packs in parallel (76.8kWh)', '5-Year Manufacturer Replacement Warranty'],
    'Residential backup, 3-5kVA inverters, daily cycling, compact wall installations',
    '₦1,380,000',
    'mid',
    true,
    '/products/alpsolar/alp-bat-livo-y-5kwh.webp',
    ARRAY['battery', 'lithium battery', 'lifepo4', 'alpsolarr', 'livo-y', '5kwh', '51.2v', '100ah'],
    '{"Model":"Livo-Y 5.12KWH","Total Energy":"5.12 kWh","Nominal Voltage":"51.2 Vdc (Operating Range: 44.8V - 57.6V)","Rated Capacity":"100 Ah","Cell Chemistry":"Lithium Iron Phosphate (LiFePO4)","Cycle Life":"≥ 6,000 Cycles @ 80% DoD, 25°C","Parallel Scalability":"Up to 15 Units in Parallel","End User Price (1-10 Units)":"₦1,440,000","Installer Price (10-20 Units)":"₦1,380,000","Dealer Price (20-40 Units)":"₦1,260,000","Promotional Installer Price":"₦1,056,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    30,
    60
),
(
    'c0000000-0000-0000-0000-000000000008',
    'AlpSolarr Livo-16E 16kWh 51.2V (312Ah) LiFePO4 Lithium Battery',
    'Batteries',
    'AlpSolarr Livo Series',
    '16kWh 51.2V high-capacity floor-standing LiFePO4 battery system with heavy-duty caster wheels for easy placement. Equipped with smart LCD touch telemetry, 1C peak discharge rating, intelligent active balancing BMS, and a 5-Year replacement warranty.',
    ARRAY['Massive 16kWh energy capacity in a single compact wheeled enclosure', 'Heavy-duty locking caster wheels for rapid', 'effortless positioning and relocation', 'Over 6', '000 deep cycle lifespan backed by automotive grade LiFePO4 chemistry', 'High continuous charge/discharge capability supporting large 8kW–16kW inverters', 'Comprehensive multi-protocol CAN/RS485 BMS communicating with all major hybrid inverters', '5-Year Manufacturer Replacement Warranty'],
    'Duplexes, large residences, mini-estates, commercial backup, heavy daytime cycling',
    '₦2,400,000',
    'premium',
    true,
    '/products/alpsolar/alp-bat-livo-16e-16kwh.webp',
    ARRAY['battery', 'lithium battery', 'lifepo4', 'alpsolarr', 'livo-16e', '16kwh', '51.2v'],
    '{"Model":"Livo-16E","Total Energy":"16.0 kWh","Nominal Voltage":"51.2 Vdc (44.8V - 57.6V Range)","Rated Capacity":"312 Ah","Mounting / Form Factor":"Floor-Standing with Industrial Caster Wheels","Cycle Life":"≥ 6,000 Cycles @ 80% DoD","Communication Ports":"CAN / RS485 / RS232","Installer Price":"₦2,400,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    16,
    60
),
(
    'c0000000-0000-0000-0000-000000000009',
    'AlpSolarr Livo 16 Pro 16kWh 51.2V Heavy-Duty LiFePO4 Battery System',
    'Batteries',
    'AlpSolarr Livo Series',
    'Premium edition 16kWh 51.2V commercial-grade energy storage system featuring dual-circuit BMS redundancy, interactive color touchscreen status console, and 7,000+ cycle lifespan. Engineered for uninterrupted operations.',
    ARRAY['16kWh usable capacity with high-rate 200A continuous discharge current', 'Interactive color front touchscreen displaying real-time cell voltages and telemetry', 'Advanced active thermal and cell balancing management system', 'Rugged floor cabinet with industrial-grade locking wheels', '5-Year Manufacturer Replacement Warranty'],
    'Commercial facilities, mission-critical infrastructure, large villas',
    '₦2,820,000',
    'premium',
    true,
    '/products/alpsolar/alp-bat-livo-16-pro-16kwh.webp',
    ARRAY['battery', 'lithium battery', 'alpsolarr', 'livo 16 pro', '16kwh'],
    '{"Model":"Livo 16 Pro","Total Energy":"16.0 kWh","Nominal Voltage":"51.2 Vdc","Rated Capacity":"312 Ah","Display":"Interactive Color LCD Touchscreen","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    10,
    60
),
(
    'c0000000-0000-0000-0000-000000000010',
    'AlpSolarr PowerGoo 2000 2kWh Portable Energy Storage Station',
    'Home Automation',
    'AlpSolarr PowerGoo Series',
    '2,048Wh high-capacity portable solar power station with 2,400W pure sine wave AC inverter, ultra-fast 1.5-hour AC wall recharging, and multi-port DC, USB-C PD 100W, and solar PV charging. Perfect for mobile power, field events, camping, and emergency domestic backup.',
    ARRAY['2', '048Wh LiFePO4 battery pack with 3', '500+ cycle lifespan', '2', '400W continuous pure sine wave AC output (4', '800W surge)', 'Ultra-fast bidirectional wall charging: 0 to 80% in only 70 minutes', 'Multiple output ports: 4x AC 230V outlets', '2x USB-C 100W PD', '4x USB-A QC 3.0', '12V car outlet', 'Integrated MPPT solar charge input accepting up to 800W of solar panels', '3-Year Manufacturer Warranty'],
    'Mobile professionals, outdoor shoots, medical clinics, emergency home power, camping',
    '₦1,440,000',
    'mid',
    true,
    '/products/alpsolar/alp-ess-powergoo-2000.webp',
    ARRAY['portable power station', 'powergoo', 'alpsolarr', '2kwh', 'generator alternative', 'camping'],
    '{"Model":"PowerGoo 2000","Battery Capacity":"2,048 Wh (LiFePO4)","AC Output":"2,400W Continuous (4,800W Peak Surge)","Solar Charging Input":"Up to 800W MPPT (12V - 60V)","Cycle Life":"3,500+ Cycles to 80% Capacity","Weight":"22.5 kg","Warranty":"3-Year Manufacturer Warranty"}'::jsonb,
    20,
    36
),
(
    'c0000000-0000-0000-0000-000000000011',
    'AlpSolarr PowerGoo 1000 1kWh Portable Energy Storage Station',
    'Home Automation',
    'AlpSolarr PowerGoo Series',
    '1,024Wh portable LiFePO4 power station featuring 1,200W AC inverter, dual fast-charging USB-C ports, and silent, fume-free operation. The ideal lightweight mobile backup power source.',
    ARRAY['1', '024Wh long-life LiFePO4 battery core (3', '000+ cycles)', '1', '200W pure sine wave AC output power', 'Lightweight ergonomic carry handle design', 'Solar MPPT input up to 400W for quick off-grid replenishment', '3-Year Manufacturer Warranty'],
    'Workstations, laptops, Wi-Fi routers, TV, outdoor activities, remote work',
    '₦864,000',
    'affordable',
    true,
    '/products/alpsolar/alp-ess-powergoo-1000.webp',
    ARRAY['portable power station', 'powergoo', 'alpsolarr', '1kwh', 'emergency power'],
    '{"Model":"PowerGoo 1000","Battery Capacity":"1,024 Wh (LiFePO4)","AC Output":"1,200W Continuous","Solar Input":"Up to 400W MPPT","Weight":"11.8 kg","Warranty":"3-Year Manufacturer Warranty"}'::jsonb,
    15,
    36
),
(
    'c0000000-0000-0000-0000-000000000012',
    'AlpSolarr PO-01 Smart Wi-Fi & Cloud Telemetry Monitoring Module',
    'Home Automation',
    'AlpSolarr Accessories',
    'Plug-and-play smart Wi-Fi telemetry module for AlpSolarr Pulse and ROSA series inverters. Enables real-time mobile app energy tracking, remote parameter configuration, power flow animation, and instant fault notification.',
    ARRAY['Direct plug-and-play connection via dedicated inverter communication port', 'Connects to 2.4GHz Wi-Fi with high-gain internal antenna', 'Real-time mobile tracking via Ligoo Smart / AlpSolarr Cloud App (iOS & Android)', 'Detailed historical solar production', 'battery state-of-charge', 'and consumption graphs', 'Instant push notifications for grid loss', 'faults', 'or abnormal battery temperatures', '2-Year Replacement Warranty'],
    'All AlpSolarr Pulse S2, S3, S4, and ROSA G2/T2 inverter owners',
    '₦50,400',
    'affordable',
    true,
    '/products/alpsolar/alp-acc-po-01-wifi.webp',
    ARRAY['wifi module', 'monitoring', 'alpsolarr', 'dongle', 'cloud monitoring', 'po-01'],
    '{"Model":"PO-01 Wi-Fi","Interface":"Inverter Multi-Pin Communication Port","Wireless Standard":"802.11 b/g/n (2.4 GHz)","App Compatibility":"iOS & Android (Ligoo Smart / AlpSolarr)","Warranty":"2-Year Replacement Warranty"}'::jsonb,
    50,
    24
),
(
    'c0000000-0000-0000-0000-000000000013',
    'Taico 5kWh 51.2V (100Ah) Wall-Mounted LiFePO4 Lithium Battery',
    'Batteries',
    'Taico Energy Storage',
    '5kWh 51.2V 100Ah wall-mounted deep-cycle LiFePO4 battery pack featuring sleek modern casing, front LCD telemetry, 6,000 cycle life, and broad multi-inverter compatibility. Sourced directly from official Nigerian distribution.',
    ARRAY['5.12kWh total capacity with 51.2V nominal voltage and 100Ah rating', 'Wall-mounted space-saving architecture with heavy-duty mounting bracket', 'Over 6', '000 charge/discharge cycles at 80% depth of discharge', 'Smart BMS with multi-protocol CAN/RS485 communication', '5-Year Manufacturer Replacement Warranty'],
    'Residential solar systems, 3kVA–5kVA inverters, standard homes',
    '₦1,260,000',
    'mid',
    true,
    '/products/alpsolar/tai-bat-5kwh.webp',
    ARRAY['battery', 'taico', 'lifepo4', '5kwh', '51.2v', '100ah', 'lithium battery'],
    '{"Model":"Taico 5kWh / 51.2V 100Ah","Capacity":"5.12 kWh / 100Ah","Nominal Voltage":"51.2 Vdc","Cycle Life":"≥ 6,000 Cycles @ 80% DoD","Mounting":"Wall-Mounted","End User Price (1-10 Units)":"₦1,320,000","Installer Price (10-20 Units)":"₦1,260,000","Dealer Price (20-40 Units)":"₦1,140,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    24,
    60
),
(
    'c0000000-0000-0000-0000-000000000014',
    'Taico 10kWh 51.2V (200Ah) LiFePO4 Lithium Battery with LCD',
    'Batteries',
    'Taico Energy Storage',
    '10.24kWh 51.2V 200Ah high-capacity LiFePO4 energy storage system. Designed for whole-home uninterrupted backup with front interactive status display, premium grade prismatic cells, and smart active balancing BMS.',
    ARRAY['10.24kWh massive energy reservoir with 200Ah continuous delivery', 'Front LCD digital telemetry displaying voltage', 'current', 'SOC %', 'and alarms', 'Grade-A LiFePO4 chemistry delivering over 6', '000 cycles', 'Multi-unit parallel scalability up to 15 units (150kWh+ capacity)', '5-Year Manufacturer Replacement Warranty'],
    '4-6 bedroom residences, commercial offices, pharmacy stores, schools',
    '₦1,980,000',
    'mid',
    true,
    '/products/alpsolar/tai-bat-10kwh.webp',
    ARRAY['battery', 'taico', 'lifepo4', '10kwh', '51.2v', '200ah', 'lithium battery'],
    '{"Model":"Taico 10kWh / 51.2V 200Ah","Capacity":"10.24 kWh / 200Ah","Nominal Voltage":"51.2 Vdc","Display":"Digital LCD Screen","Cycle Life":"≥ 6,000 Cycles @ 80% DoD","End User Price (1-10 Units)":"₦2,100,000","Installer Price (10-20 Units)":"₦1,980,000","Dealer Price (20-40 Units)":"₦1,800,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    20,
    60
),
(
    'c0000000-0000-0000-0000-000000000015',
    'Taico 15kWh 51.2V (300Ah) Mobile LiFePO4 Battery with Caster Wheels',
    'Batteries',
    'Taico Energy Storage',
    '15kWh 51.2V 300Ah mobile energy storage system with integrated 360-degree roller caster wheels. Designed for easy positioning without requiring heavy wall-mounting hardware.',
    ARRAY['15kWh capacity in a mobile wheeled upright cabinet', 'Industrial lockable caster wheels for effortless relocation', 'Supports 150A continuous charge and discharge current', 'Intelligent CAN/RS485 communication with all top hybrid inverters', '5-Year Manufacturer Replacement Warranty'],
    'Large duplexes, medical centres, commercial offices, multi-inverter setups',
    '₦3,144,000',
    'premium',
    true,
    '/products/alpsolar/tai-bat-15kwh.webp',
    ARRAY['battery', 'taico', '15kwh', '51.2v', 'mobile battery', 'wheels'],
    '{"Model":"Taico 15kWh Mobile","Capacity":"15.36 kWh / 300Ah","Nominal Voltage":"51.2 Vdc","Form Factor":"Floor-Standing with Lockable Wheels","End User Price (1-10 Units)":"₦3,240,000","Installer Price (10-20 Units)":"₦3,144,000","Dealer Price (20-40 Units)":"₦3,000,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    14,
    60
),
(
    'c0000000-0000-0000-0000-000000000016',
    'Taico 20kWh 51.2V (400Ah) Mobile LiFePO4 Battery with Caster Wheels',
    'Batteries',
    'Taico Energy Storage',
    '20.48kWh 51.2V 400Ah enterprise-grade lithium energy storage unit with built-in wheels and front digital screen. Provides massive energy capacity for residential estates and commercial buildings.',
    ARRAY['20.48kWh massive capacity delivering whole-day uninterruptible autonomy', 'High-power 200A charge/discharge current handling heavy air conditioning loads', 'Heavy-duty mobile roller chassis with front access terminal bay', '5-Year Manufacturer Replacement Warranty'],
    'Commercial buildings, luxury villas, supermarkets, hotels, data centers',
    '₦3,600,000',
    'premium',
    true,
    '/products/alpsolar/tai-bat-20kwh.webp',
    ARRAY['battery', 'taico', '20kwh', '51.2v', '400ah', 'commercial battery'],
    '{"Model":"Taico 20kWh Mobile","Capacity":"20.48 kWh / 400Ah","Nominal Voltage":"51.2 Vdc","End User Price (1-10 Units)":"₦3,660,000","Installer Price (10-20 Units)":"₦3,600,000","Dealer Price (20-40 Units)":"₦3,480,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    10,
    60
),
(
    'c0000000-0000-0000-0000-000000000017',
    'Taico 28kWh 51.2V (560Ah) Commercial Mobile LiFePO4 Battery Cabinet',
    'Batteries',
    'Taico Energy Storage',
    '28.67kWh 51.2V 560Ah ultra-capacity commercial battery cabinet on heavy-duty wheels. Engineered for high-load commercial facilities, telecom towers, micro-grids, and industrial sites.',
    ARRAY['Industry-leading 28.67kWh energy density in a single mobile cabinet', '560Ah capacity with dual high-current DC disconnect breakers', 'Advanced multi-channel thermal monitoring and active cell equalization', '5-Year Manufacturer Replacement Warranty'],
    'Commercial factories, mini-grids, industrial sites, hotels, telecom towers',
    '₦4,380,000',
    'premium',
    true,
    '/products/alpsolar/tai-bat-28kwh.webp',
    ARRAY['battery', 'taico', '28kwh', '51.2v', 'commercial battery', 'microgrid'],
    '{"Model":"Taico 28kWh Commercial","Capacity":"28.67 kWh / 560Ah","Nominal Voltage":"51.2 Vdc","End User Price (1-10 Units)":"₦4,440,000","Installer Price (10-20 Units)":"₦4,380,000","Dealer Price (20-40 Units)":"₦4,320,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    8,
    60
),
(
    'c0000000-0000-0000-0000-000000000018',
    'Dawnice 5kWh 51.2V (100Ah) Wall-Mounted LiFePO4 Battery (HZEB-LCT-5)',
    'Batteries',
    'Dawnice Energy Storage',
    '5.12kWh 51.2V 100Ah ultra-slim wall-mounted lithium energy storage battery. Features intelligent BMS protection, 6,000+ cycle life, and parallel scalability up to 15 packs.',
    ARRAY['5.12kWh total capacity with 100Ah rating at 51.2V nominal', 'Ultra-slim space-saving wall-mount profile with seamless wall bracket', '6', '000+ deep cycles at 80% depth of discharge with Grade-A LiFePO4 cells', 'Smart multi-inverter protocol support via CAN/RS485', '5-Year Manufacturer Replacement Warranty'],
    'Residential backup, apartments, small homes, 3kVA–5kVA solar systems',
    '₦1,380,000',
    'mid',
    true,
    '/products/alpsolar/daw-bat-5kwh.webp',
    ARRAY['battery', 'dawnice', 'lifepo4', '5kwh', '51.2v', '100ah', 'lithium battery'],
    '{"Model":"HZEB-LCT-5","Capacity":"5.12 kWh / 100Ah","Nominal Voltage":"51.2 Vdc","Cycle Life":"≥ 6,000 Cycles","End User Price (1-10 Units)":"₦1,500,000","Installer Price (10-20 Units)":"₦1,380,000","Dealer Price (20-40 Units)":"₦1,260,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    25,
    60
),
(
    'c0000000-0000-0000-0000-000000000019',
    'Dawnice 10kWh 51.2V (200Ah) Wall-Mounted LiFePO4 Battery (HZEB-LCT-10)',
    'Batteries',
    'Dawnice Energy Storage',
    '10.24kWh 51.2V 200Ah high-capacity wall-mounted battery engineered for executive homes and commercial offices. Features integrated LED battery indicator and multi-protocol CAN/RS485 BMS.',
    ARRAY['10.24kWh energy storage capacity with 200Ah continuous output', 'Robust wall-mounted structural steel casing', '6', '000+ cycle life with Grade-A prismatic LiFePO4 cells', 'Up to 15 units parallel connection for up to 153.6kWh capacity', '5-Year Manufacturer Replacement Warranty'],
    '4-5 bedroom duplexes, commercial offices, clinics, restaurants',
    '₦2,184,000',
    'mid',
    true,
    '/products/alpsolar/daw-bat-10kwh.webp',
    ARRAY['battery', 'dawnice', 'lifepo4', '10kwh', '51.2v', '200ah', 'lithium battery'],
    '{"Model":"HZEB-LCT-10","Capacity":"10.24 kWh / 200Ah","Nominal Voltage":"51.2 Vdc","Cycle Life":"≥ 6,000 Cycles","End User Price (1-10 Units)":"₦2,280,000","Installer Price (10-20 Units)":"₦2,184,000","Dealer Price (20-40 Units)":"₦2,136,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    18,
    60
),
(
    'c0000000-0000-0000-0000-000000000020',
    'Dawnice 16kWh 51.2V (312Ah) High-Capacity LiFePO4 Battery (HZEB-LCT-16)',
    'Batteries',
    'Dawnice Energy Storage',
    '16kWh 51.2V 312Ah high-density lithium storage system. Designed to provide extended whole-day autonomy for high-consumption estates and commercial operations with a 5-Year replacement warranty.',
    ARRAY['16kWh substantial capacity in a high-density wall/floor-mount enclosure', 'Automotive-grade LiFePO4 cells with 6', '000+ cycles', 'Advanced BMS communication with Deye', 'AlpSolarr', 'Luxpower', 'and SRNE inverters', '5-Year Manufacturer Replacement Warranty'],
    'Commercial buildings, luxury villas, schools, supermarkets, hospitality',
    '₦3,336,000',
    'premium',
    true,
    '/products/alpsolar/daw-bat-16kwh.webp',
    ARRAY['battery', 'dawnice', '16kwh', '51.2v', '312ah', 'lithium battery'],
    '{"Model":"HZEB-LCT-16","Capacity":"16.0 kWh / 312Ah","Nominal Voltage":"51.2 Vdc","Cycle Life":"≥ 6,000 Cycles","End User Price (1-10 Units)":"₦3,360,000","Installer Price (10-20 Units)":"₦3,336,000","Dealer Price (20-40 Units)":"₦3,240,000","Warranty":"5-Year Replacement Warranty"}'::jsonb,
    12,
    60
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    series = EXCLUDED.series,
    description = EXCLUDED.description,
    features = EXCLUDED.features,
    best_for = EXCLUDED.best_for,
    price = EXCLUDED.price,
    tier = EXCLUDED.tier,
    is_active = EXCLUDED.is_active,
    image_url = EXCLUDED.image_url,
    tags = EXCLUDED.tags,
    specifications = EXCLUDED.specifications,
    stock_qty = EXCLUDED.stock_qty,
    warranty_months = EXCLUDED.warranty_months;
